/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type LoginDTO,
    LoginDTOFromJSON,
    LoginDTOToJSON,
} from '../models/LoginDTO';
import {
    type MaaResultListMaaUserInfo,
    MaaResultListMaaUserInfoFromJSON,
    MaaResultListMaaUserInfoToJSON,
} from '../models/MaaResultListMaaUserInfo';
import {
    type MaaResultMaaLoginRsp,
    MaaResultMaaLoginRspFromJSON,
    MaaResultMaaLoginRspToJSON,
} from '../models/MaaResultMaaLoginRsp';
import {
    type MaaResultMaaUserInfo,
    MaaResultMaaUserInfoFromJSON,
    MaaResultMaaUserInfoToJSON,
} from '../models/MaaResultMaaUserInfo';
import {
    type MaaResultUnit,
    MaaResultUnitFromJSON,
    MaaResultUnitToJSON,
} from '../models/MaaResultUnit';
import {
    type PasswordResetDTO,
    PasswordResetDTOFromJSON,
    PasswordResetDTOToJSON,
} from '../models/PasswordResetDTO';
import {
    type PasswordResetVCodeDTO,
    PasswordResetVCodeDTOFromJSON,
    PasswordResetVCodeDTOToJSON,
} from '../models/PasswordResetVCodeDTO';
import {
    type PasswordUpdateDTO,
    PasswordUpdateDTOFromJSON,
    PasswordUpdateDTOToJSON,
} from '../models/PasswordUpdateDTO';
import {
    type RefreshReq,
    RefreshReqFromJSON,
    RefreshReqToJSON,
} from '../models/RefreshReq';
import {
    type RegisterDTO,
    RegisterDTOFromJSON,
    RegisterDTOToJSON,
} from '../models/RegisterDTO';
import {
    type SendRegistrationTokenDTO,
    SendRegistrationTokenDTOFromJSON,
    SendRegistrationTokenDTOToJSON,
} from '../models/SendRegistrationTokenDTO';
import {
    type UserInfoUpdateDTO,
    UserInfoUpdateDTOFromJSON,
    UserInfoUpdateDTOToJSON,
} from '../models/UserInfoUpdateDTO';

export interface GetBatchUserInfoRequest {
    ids: Array<number>;
}

export interface GetUserInfoRequest {
    userId: string;
}

export interface LoginRequest {
    loginDTO: LoginDTO;
}

export interface PasswordResetRequest {
    passwordResetDTO: PasswordResetDTO;
}

export interface PasswordResetRequestRequest {
    passwordResetVCodeDTO: PasswordResetVCodeDTO;
}

export interface RefreshRequest {
    refreshReq: RefreshReq;
}

export interface RegisterRequest {
    registerDTO: RegisterDTO;
}

export interface SearchUsersRequest {
    userName: string;
    page?: number;
    size?: number;
}

export interface SendRegistrationTokenRequest {
    sendRegistrationTokenDTO: SendRegistrationTokenDTO;
}

export interface UpdateInfoRequest {
    userInfoUpdateDTO: UserInfoUpdateDTO;
}

export interface UpdatePasswordRequest {
    passwordUpdateDTO: PasswordUpdateDTO;
}

/**
 * 
 */
export class CopilotUserApi extends runtime.BaseAPI {

    /**
     * Creates request options for getBatchUserInfo without sending the request
     */
    async getBatchUserInfoRequestOpts(requestParameters: GetBatchUserInfoRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ids'] == null) {
            throw new runtime.RequiredError(
                'ids',
                'Required parameter "ids" was null or undefined when calling getBatchUserInfo().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['ids'] != null) {
            queryParameters['ids'] = requestParameters['ids'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/user/batch`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 批量获取用户信息
     * 批量获取用户信息
     */
    async getBatchUserInfoRaw(requestParameters: GetBatchUserInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResultListMaaUserInfo>> {
        const requestOptions = await this.getBatchUserInfoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultListMaaUserInfoFromJSON(jsonValue));
    }

    /**
     * 批量获取用户信息
     * 批量获取用户信息
     */
    async getBatchUserInfo(requestParameters: GetBatchUserInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResultListMaaUserInfo> {
        const response = await this.getBatchUserInfoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMe without sending the request
     */
    async getMeRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/user/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 获取当前登录用户信息
     * 获取当前登录用户信息
     */
    async getMeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResultMaaUserInfo>> {
        const requestOptions = await this.getMeRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultMaaUserInfoFromJSON(jsonValue));
    }

    /**
     * 获取当前登录用户信息
     * 获取当前登录用户信息
     */
    async getMe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResultMaaUserInfo> {
        const response = await this.getMeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getUserInfo without sending the request
     */
    async getUserInfoRequestOpts(requestParameters: GetUserInfoRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getUserInfo().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/user/info`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 查询用户信息（附带与当前用户的关系）
     * 查询用户信息
     */
    async getUserInfoRaw(requestParameters: GetUserInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResultMaaUserInfo>> {
        const requestOptions = await this.getUserInfoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultMaaUserInfoFromJSON(jsonValue));
    }

    /**
     * 查询用户信息（附带与当前用户的关系）
     * 查询用户信息
     */
    async getUserInfo(requestParameters: GetUserInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResultMaaUserInfo> {
        const response = await this.getUserInfoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for login without sending the request
     */
    async loginRequestOpts(requestParameters: LoginRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['loginDTO'] == null) {
            throw new runtime.RequiredError(
                'loginDTO',
                'Required parameter "loginDTO" was null or undefined when calling login().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/user/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginDTOToJSON(requestParameters['loginDTO']),
        };
    }

    /**
     * 用户登录
     * 用户登录
     */
    async loginRaw(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResultMaaLoginRsp>> {
        const requestOptions = await this.loginRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultMaaLoginRspFromJSON(jsonValue));
    }

    /**
     * 用户登录
     * 用户登录
     */
    async login(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResultMaaLoginRsp> {
        const response = await this.loginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for passwordReset without sending the request
     */
    async passwordResetRequestOpts(requestParameters: PasswordResetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['passwordResetDTO'] == null) {
            throw new runtime.RequiredError(
                'passwordResetDTO',
                'Required parameter "passwordResetDTO" was null or undefined when calling passwordReset().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/user/password/reset`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PasswordResetDTOToJSON(requestParameters['passwordResetDTO']),
        };
    }

    /**
     * 邮箱重置密码
     * 重置密码
     */
    async passwordResetRaw(requestParameters: PasswordResetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResultUnit>> {
        const requestOptions = await this.passwordResetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultUnitFromJSON(jsonValue));
    }

    /**
     * 邮箱重置密码
     * 重置密码
     */
    async passwordReset(requestParameters: PasswordResetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResultUnit> {
        const response = await this.passwordResetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for passwordResetRequest without sending the request
     */
    async passwordResetRequestRequestOpts(requestParameters: PasswordResetRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['passwordResetVCodeDTO'] == null) {
            throw new runtime.RequiredError(
                'passwordResetVCodeDTO',
                'Required parameter "passwordResetVCodeDTO" was null or undefined when calling passwordResetRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/user/password/reset_request`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PasswordResetVCodeDTOToJSON(requestParameters['passwordResetVCodeDTO']),
        };
    }

    /**
     * 验证码重置密码功能：  发送验证码用于重置
     * 发送用于重置密码的验证码
     */
    async passwordResetRequestRaw(requestParameters: PasswordResetRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResultUnit>> {
        const requestOptions = await this.passwordResetRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultUnitFromJSON(jsonValue));
    }

    /**
     * 验证码重置密码功能：  发送验证码用于重置
     * 发送用于重置密码的验证码
     */
    async passwordResetRequest(requestParameters: PasswordResetRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResultUnit> {
        const response = await this.passwordResetRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for refresh without sending the request
     */
    async refreshRequestOpts(requestParameters: RefreshRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['refreshReq'] == null) {
            throw new runtime.RequiredError(
                'refreshReq',
                'Required parameter "refreshReq" was null or undefined when calling refresh().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/user/refresh`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RefreshReqToJSON(requestParameters['refreshReq']),
        };
    }

    /**
     * 刷新token
     * 刷新token
     */
    async refreshRaw(requestParameters: RefreshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResultMaaLoginRsp>> {
        const requestOptions = await this.refreshRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultMaaLoginRspFromJSON(jsonValue));
    }

    /**
     * 刷新token
     * 刷新token
     */
    async refresh(requestParameters: RefreshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResultMaaLoginRsp> {
        const response = await this.refreshRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for register without sending the request
     */
    async registerRequestOpts(requestParameters: RegisterRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['registerDTO'] == null) {
            throw new runtime.RequiredError(
                'registerDTO',
                'Required parameter "registerDTO" was null or undefined when calling register().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/user/register`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterDTOToJSON(requestParameters['registerDTO']),
        };
    }

    /**
     * 用户注册
     * 用户注册
     */
    async registerRaw(requestParameters: RegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResultMaaUserInfo>> {
        const requestOptions = await this.registerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultMaaUserInfoFromJSON(jsonValue));
    }

    /**
     * 用户注册
     * 用户注册
     */
    async register(requestParameters: RegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResultMaaUserInfo> {
        const response = await this.registerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for searchUsers without sending the request
     */
    async searchUsersRequestOpts(requestParameters: SearchUsersRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userName'] == null) {
            throw new runtime.RequiredError(
                'userName',
                'Required parameter "userName" was null or undefined when calling searchUsers().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userName'] != null) {
            queryParameters['userName'] = requestParameters['userName'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/user/search`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 用户模糊搜索
     * 用户模糊搜索
     */
    async searchUsersRaw(requestParameters: SearchUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResultListMaaUserInfo>> {
        const requestOptions = await this.searchUsersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultListMaaUserInfoFromJSON(jsonValue));
    }

    /**
     * 用户模糊搜索
     * 用户模糊搜索
     */
    async searchUsers(requestParameters: SearchUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResultListMaaUserInfo> {
        const response = await this.searchUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sendRegistrationToken without sending the request
     */
    async sendRegistrationTokenRequestOpts(requestParameters: SendRegistrationTokenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sendRegistrationTokenDTO'] == null) {
            throw new runtime.RequiredError(
                'sendRegistrationTokenDTO',
                'Required parameter "sendRegistrationTokenDTO" was null or undefined when calling sendRegistrationToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/user/sendRegistrationToken`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendRegistrationTokenDTOToJSON(requestParameters['sendRegistrationTokenDTO']),
        };
    }

    /**
     * 获得注册时的验证码
     * 注册时发送验证码
     */
    async sendRegistrationTokenRaw(requestParameters: SendRegistrationTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResultUnit>> {
        const requestOptions = await this.sendRegistrationTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultUnitFromJSON(jsonValue));
    }

    /**
     * 获得注册时的验证码
     * 注册时发送验证码
     */
    async sendRegistrationToken(requestParameters: SendRegistrationTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResultUnit> {
        const response = await this.sendRegistrationTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateInfo without sending the request
     */
    async updateInfoRequestOpts(requestParameters: UpdateInfoRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userInfoUpdateDTO'] == null) {
            throw new runtime.RequiredError(
                'userInfoUpdateDTO',
                'Required parameter "userInfoUpdateDTO" was null or undefined when calling updateInfo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/user/update/info`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserInfoUpdateDTOToJSON(requestParameters['userInfoUpdateDTO']),
        };
    }

    /**
     * 更新用户详细信息
     * 更新用户详细信息
     */
    async updateInfoRaw(requestParameters: UpdateInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResultUnit>> {
        const requestOptions = await this.updateInfoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultUnitFromJSON(jsonValue));
    }

    /**
     * 更新用户详细信息
     * 更新用户详细信息
     */
    async updateInfo(requestParameters: UpdateInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResultUnit> {
        const response = await this.updateInfoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updatePassword without sending the request
     */
    async updatePasswordRequestOpts(requestParameters: UpdatePasswordRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['passwordUpdateDTO'] == null) {
            throw new runtime.RequiredError(
                'passwordUpdateDTO',
                'Required parameter "passwordUpdateDTO" was null or undefined when calling updatePassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/user/update/password`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PasswordUpdateDTOToJSON(requestParameters['passwordUpdateDTO']),
        };
    }

    /**
     * 根据原密码
     * 修改当前用户密码
     */
    async updatePasswordRaw(requestParameters: UpdatePasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResultUnit>> {
        const requestOptions = await this.updatePasswordRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultUnitFromJSON(jsonValue));
    }

    /**
     * 根据原密码
     * 修改当前用户密码
     */
    async updatePassword(requestParameters: UpdatePasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResultUnit> {
        const response = await this.updatePasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
