/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CopilotCUDRequest,
    CopilotCUDRequestFromJSON,
    CopilotCUDRequestToJSON,
} from '../models/CopilotCUDRequest';
import {
    type CopilotRatingReq,
    CopilotRatingReqFromJSON,
    CopilotRatingReqToJSON,
} from '../models/CopilotRatingReq';
import {
    type MaaResultCopilotInfo,
    MaaResultCopilotInfoFromJSON,
    MaaResultCopilotInfoToJSON,
} from '../models/MaaResultCopilotInfo';
import {
    type MaaResultCopilotPageInfo,
    MaaResultCopilotPageInfoFromJSON,
    MaaResultCopilotPageInfoToJSON,
} from '../models/MaaResultCopilotPageInfo';
import {
    type MaaResultLong,
    MaaResultLongFromJSON,
    MaaResultLongToJSON,
} from '../models/MaaResultLong';
import {
    type MaaResultString,
    MaaResultStringFromJSON,
    MaaResultStringToJSON,
} from '../models/MaaResultString';
import {
    type MaaResultUnit,
    MaaResultUnitFromJSON,
    MaaResultUnitToJSON,
} from '../models/MaaResultUnit';

export interface BanCommentsRequest {
    copilotId: number;
    status: BanCommentsStatusEnum;
}

export interface DeleteCopilotRequest {
    copilotCUDRequest: CopilotCUDRequest;
}

export interface GetCopilotByIdRequest {
    id: number;
}

export interface ModifyStatusRequest {
    id: number;
    status: boolean;
}

export interface QueriesCopilotRequest {
    page?: number;
    limit?: number;
    levelKeyword?: string;
    operator?: string;
    content?: string;
    document?: string;
    uploaderId?: string;
    desc?: boolean;
    orderBy?: string;
    language?: string;
    copilotIds?: Array<number>;
    status?: QueriesCopilotStatusEnum;
    onlyFollowing?: boolean;
}

export interface RatesCopilotOperationRequest {
    copilotRatingReq: CopilotRatingReq;
}

export interface UpdateCopilotRequest {
    copilotCUDRequest: CopilotCUDRequest;
}

export interface UploadCopilotRequest {
    copilotCUDRequest: CopilotCUDRequest;
}

/**
 * 
 */
export class CopilotControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for banComments without sending the request
     */
    async banCommentsRequestOpts(requestParameters: BanCommentsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['copilotId'] == null) {
            throw new runtime.RequiredError(
                'copilotId',
                'Required parameter "copilotId" was null or undefined when calling banComments().'
            );
        }

        if (requestParameters['status'] == null) {
            throw new runtime.RequiredError(
                'status',
                'Required parameter "status" was null or undefined when calling banComments().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['copilotId'] != null) {
            queryParameters['copilotId'] = requestParameters['copilotId'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/copilot/ban`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 禁用评论区/开启评论区
     */
    async banCommentsRaw(requestParameters: BanCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResultString>> {
        const requestOptions = await this.banCommentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultStringFromJSON(jsonValue));
    }

    /**
     * 禁用评论区/开启评论区
     */
    async banComments(requestParameters: BanCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResultString> {
        const response = await this.banCommentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteCopilot without sending the request
     */
    async deleteCopilotRequestOpts(requestParameters: DeleteCopilotRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['copilotCUDRequest'] == null) {
            throw new runtime.RequiredError(
                'copilotCUDRequest',
                'Required parameter "copilotCUDRequest" was null or undefined when calling deleteCopilot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/copilot/delete`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CopilotCUDRequestToJSON(requestParameters['copilotCUDRequest']),
        };
    }

    /**
     * 删除作业
     */
    async deleteCopilotRaw(requestParameters: DeleteCopilotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResultUnit>> {
        const requestOptions = await this.deleteCopilotRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultUnitFromJSON(jsonValue));
    }

    /**
     * 删除作业
     */
    async deleteCopilot(requestParameters: DeleteCopilotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResultUnit> {
        const response = await this.deleteCopilotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCopilotById without sending the request
     */
    async getCopilotByIdRequestOpts(requestParameters: GetCopilotByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getCopilotById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/copilot/get/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 获取作业
     */
    async getCopilotByIdRaw(requestParameters: GetCopilotByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResultCopilotInfo>> {
        const requestOptions = await this.getCopilotByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultCopilotInfoFromJSON(jsonValue));
    }

    /**
     * 获取作业
     */
    async getCopilotById(requestParameters: GetCopilotByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResultCopilotInfo> {
        const response = await this.getCopilotByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for modifyStatus without sending the request
     */
    async modifyStatusRequestOpts(requestParameters: ModifyStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling modifyStatus().'
            );
        }

        if (requestParameters['status'] == null) {
            throw new runtime.RequiredError(
                'status',
                'Required parameter "status" was null or undefined when calling modifyStatus().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/copilot/status`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 修改通知状态
     */
    async modifyStatusRaw(requestParameters: ModifyStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResultString>> {
        const requestOptions = await this.modifyStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultStringFromJSON(jsonValue));
    }

    /**
     * 修改通知状态
     */
    async modifyStatus(requestParameters: ModifyStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResultString> {
        const response = await this.modifyStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for queriesCopilot without sending the request
     */
    async queriesCopilotRequestOpts(requestParameters: QueriesCopilotRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['levelKeyword'] != null) {
            queryParameters['levelKeyword'] = requestParameters['levelKeyword'];
        }

        if (requestParameters['operator'] != null) {
            queryParameters['operator'] = requestParameters['operator'];
        }

        if (requestParameters['content'] != null) {
            queryParameters['content'] = requestParameters['content'];
        }

        if (requestParameters['document'] != null) {
            queryParameters['document'] = requestParameters['document'];
        }

        if (requestParameters['uploaderId'] != null) {
            queryParameters['uploaderId'] = requestParameters['uploaderId'];
        }

        if (requestParameters['desc'] != null) {
            queryParameters['desc'] = requestParameters['desc'];
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['orderBy'] = requestParameters['orderBy'];
        }

        if (requestParameters['language'] != null) {
            queryParameters['language'] = requestParameters['language'];
        }

        if (requestParameters['copilotIds'] != null) {
            queryParameters['copilotIds'] = requestParameters['copilotIds'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['onlyFollowing'] != null) {
            queryParameters['onlyFollowing'] = requestParameters['onlyFollowing'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/copilot/query`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 分页查询作业，提供登录凭据时查询用户自己的作业
     */
    async queriesCopilotRaw(requestParameters: QueriesCopilotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResultCopilotPageInfo>> {
        const requestOptions = await this.queriesCopilotRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultCopilotPageInfoFromJSON(jsonValue));
    }

    /**
     * 分页查询作业，提供登录凭据时查询用户自己的作业
     */
    async queriesCopilot(requestParameters: QueriesCopilotRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResultCopilotPageInfo> {
        const response = await this.queriesCopilotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ratesCopilotOperation without sending the request
     */
    async ratesCopilotOperationRequestOpts(requestParameters: RatesCopilotOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['copilotRatingReq'] == null) {
            throw new runtime.RequiredError(
                'copilotRatingReq',
                'Required parameter "copilotRatingReq" was null or undefined when calling ratesCopilotOperation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/copilot/rating`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CopilotRatingReqToJSON(requestParameters['copilotRatingReq']),
        };
    }

    /**
     * 为作业评分
     */
    async ratesCopilotOperationRaw(requestParameters: RatesCopilotOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResultString>> {
        const requestOptions = await this.ratesCopilotOperationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultStringFromJSON(jsonValue));
    }

    /**
     * 为作业评分
     */
    async ratesCopilotOperation(requestParameters: RatesCopilotOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResultString> {
        const response = await this.ratesCopilotOperationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateCopilot without sending the request
     */
    async updateCopilotRequestOpts(requestParameters: UpdateCopilotRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['copilotCUDRequest'] == null) {
            throw new runtime.RequiredError(
                'copilotCUDRequest',
                'Required parameter "copilotCUDRequest" was null or undefined when calling updateCopilot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/copilot/update`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CopilotCUDRequestToJSON(requestParameters['copilotCUDRequest']),
        };
    }

    /**
     * 更新作业
     */
    async updateCopilotRaw(requestParameters: UpdateCopilotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResultUnit>> {
        const requestOptions = await this.updateCopilotRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultUnitFromJSON(jsonValue));
    }

    /**
     * 更新作业
     */
    async updateCopilot(requestParameters: UpdateCopilotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResultUnit> {
        const response = await this.updateCopilotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for uploadCopilot without sending the request
     */
    async uploadCopilotRequestOpts(requestParameters: UploadCopilotRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['copilotCUDRequest'] == null) {
            throw new runtime.RequiredError(
                'copilotCUDRequest',
                'Required parameter "copilotCUDRequest" was null or undefined when calling uploadCopilot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/copilot/upload`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CopilotCUDRequestToJSON(requestParameters['copilotCUDRequest']),
        };
    }

    /**
     * 上传作业
     */
    async uploadCopilotRaw(requestParameters: UploadCopilotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResultLong>> {
        const requestOptions = await this.uploadCopilotRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultLongFromJSON(jsonValue));
    }

    /**
     * 上传作业
     */
    async uploadCopilot(requestParameters: UploadCopilotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResultLong> {
        const response = await this.uploadCopilotRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const BanCommentsStatusEnum = {
    Enabled: 'ENABLED',
    Disabled: 'DISABLED'
} as const;
export type BanCommentsStatusEnum = typeof BanCommentsStatusEnum[keyof typeof BanCommentsStatusEnum];
/**
 * @export
 */
export const QueriesCopilotStatusEnum = {
    Private: 'PRIVATE',
    Public: 'PUBLIC'
} as const;
export type QueriesCopilotStatusEnum = typeof QueriesCopilotStatusEnum[keyof typeof QueriesCopilotStatusEnum];
