/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type MaaResult,
    MaaResultFromJSON,
    MaaResultToJSON,
} from '../models/MaaResult';
import {
    type MaaResultMaaSystemInfo,
    MaaResultMaaSystemInfoFromJSON,
    MaaResultMaaSystemInfoToJSON,
} from '../models/MaaResultMaaSystemInfo';
import {
    type MaaResultMapStringCacheStatInfo,
    MaaResultMapStringCacheStatInfoFromJSON,
    MaaResultMapStringCacheStatInfoToJSON,
} from '../models/MaaResultMapStringCacheStatInfo';

/**
 * 
 */
export class SystemApi extends runtime.BaseAPI {

    /**
     * Creates request options for getIntraProcessCacheStat without sending the request
     */
    async getIntraProcessCacheStatRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/cache/stat`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 返回进程内缓存统计信息
     * 返回进程内缓存统计信息
     */
    async getIntraProcessCacheStatRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResultMapStringCacheStatInfo>> {
        const requestOptions = await this.getIntraProcessCacheStatRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultMapStringCacheStatInfoFromJSON(jsonValue));
    }

    /**
     * 返回进程内缓存统计信息
     * 返回进程内缓存统计信息
     */
    async getIntraProcessCacheStat(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResultMapStringCacheStatInfo> {
        const response = await this.getIntraProcessCacheStatRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSystemVersion without sending the request
     */
    async getSystemVersionRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/version`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets the current version of the server.
     * Gets the current version of the server.
     */
    async getSystemVersionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResultMaaSystemInfo>> {
        const requestOptions = await this.getSystemVersionRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultMaaSystemInfoFromJSON(jsonValue));
    }

    /**
     * Gets the current version of the server.
     * Gets the current version of the server.
     */
    async getSystemVersion(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResultMaaSystemInfo> {
        const response = await this.getSystemVersionRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for test without sending the request
     */
    async testRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Tests if the server is ready.
     * Tests if the server is ready.
     */
    async testRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResult>> {
        const requestOptions = await this.testRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultFromJSON(jsonValue));
    }

    /**
     * Tests if the server is ready.
     * Tests if the server is ready.
     */
    async test(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResult> {
        const response = await this.testRaw(initOverrides);
        return await response.value();
    }

}
