/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type MaaResultPagedDTOMaaUserInfo,
    MaaResultPagedDTOMaaUserInfoFromJSON,
    MaaResultPagedDTOMaaUserInfoToJSON,
} from '../models/MaaResultPagedDTOMaaUserInfo';
import {
    type MaaResultUnit,
    MaaResultUnitFromJSON,
    MaaResultUnitToJSON,
} from '../models/MaaResultUnit';

export interface FollowRequest {
    followUserId: number;
}

export interface GetFansListRequest {
    page?: number;
    size?: number;
}

export interface GetFollowingListRequest {
    page?: number;
    size?: number;
}

export interface UnfollowRequest {
    followUserId: number;
}

/**
 * 
 */
export class UserFollowApi extends runtime.BaseAPI {

    /**
     * Creates request options for follow without sending the request
     */
    async followRequestOpts(requestParameters: FollowRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['followUserId'] == null) {
            throw new runtime.RequiredError(
                'followUserId',
                'Required parameter "followUserId" was null or undefined when calling follow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/follow/follow/{followUserId}`;
        urlPath = urlPath.replace('{followUserId}', encodeURIComponent(String(requestParameters['followUserId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 关注用户
     */
    async followRaw(requestParameters: FollowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResultUnit>> {
        const requestOptions = await this.followRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultUnitFromJSON(jsonValue));
    }

    /**
     * 关注用户
     */
    async follow(requestParameters: FollowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResultUnit> {
        const response = await this.followRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFansList without sending the request
     */
    async getFansListRequestOpts(requestParameters: GetFansListRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/follow/fansList`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 获取粉丝列表
     */
    async getFansListRaw(requestParameters: GetFansListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResultPagedDTOMaaUserInfo>> {
        const requestOptions = await this.getFansListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultPagedDTOMaaUserInfoFromJSON(jsonValue));
    }

    /**
     * 获取粉丝列表
     */
    async getFansList(requestParameters: GetFansListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResultPagedDTOMaaUserInfo> {
        const response = await this.getFansListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFollowingList without sending the request
     */
    async getFollowingListRequestOpts(requestParameters: GetFollowingListRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/follow/followingList`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 获取关注列表
     */
    async getFollowingListRaw(requestParameters: GetFollowingListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResultPagedDTOMaaUserInfo>> {
        const requestOptions = await this.getFollowingListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultPagedDTOMaaUserInfoFromJSON(jsonValue));
    }

    /**
     * 获取关注列表
     */
    async getFollowingList(requestParameters: GetFollowingListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResultPagedDTOMaaUserInfo> {
        const response = await this.getFollowingListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for unfollow without sending the request
     */
    async unfollowRequestOpts(requestParameters: UnfollowRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['followUserId'] == null) {
            throw new runtime.RequiredError(
                'followUserId',
                'Required parameter "followUserId" was null or undefined when calling unfollow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/follow/unfollow/{followUserId}`;
        urlPath = urlPath.replace('{followUserId}', encodeURIComponent(String(requestParameters['followUserId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 取消关注
     */
    async unfollowRaw(requestParameters: UnfollowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaaResultUnit>> {
        const requestOptions = await this.unfollowRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaaResultUnitFromJSON(jsonValue));
    }

    /**
     * 取消关注
     */
    async unfollow(requestParameters: UnfollowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaaResultUnit> {
        const response = await this.unfollowRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
