/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CacheStatInfo
 */
export interface CacheStatInfo {
    /**
     * 
     * @type {number}
     * @memberof CacheStatInfo
     */
    hitRate?: number;
    /**
     * 
     * @type {number}
     * @memberof CacheStatInfo
     */
    missRate?: number;
    /**
     * 
     * @type {number}
     * @memberof CacheStatInfo
     */
    hitCount?: number;
    /**
     * 
     * @type {number}
     * @memberof CacheStatInfo
     */
    missCount?: number;
    /**
     * 
     * @type {number}
     * @memberof CacheStatInfo
     */
    loadCount?: number;
    /**
     * 
     * @type {number}
     * @memberof CacheStatInfo
     */
    evictionCount?: number;
    /**
     * 
     * @type {number}
     * @memberof CacheStatInfo
     */
    averageLoadPenalty?: number;
}

/**
 * Check if a given object implements the CacheStatInfo interface.
 */
export function instanceOfCacheStatInfo(value: object): value is CacheStatInfo {
    return true;
}

export function CacheStatInfoFromJSON(json: any): CacheStatInfo {
    return CacheStatInfoFromJSONTyped(json, false);
}

export function CacheStatInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheStatInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'hitRate': json['hitRate'] == null ? undefined : json['hitRate'],
        'missRate': json['missRate'] == null ? undefined : json['missRate'],
        'hitCount': json['hitCount'] == null ? undefined : json['hitCount'],
        'missCount': json['missCount'] == null ? undefined : json['missCount'],
        'loadCount': json['loadCount'] == null ? undefined : json['loadCount'],
        'evictionCount': json['evictionCount'] == null ? undefined : json['evictionCount'],
        'averageLoadPenalty': json['averageLoadPenalty'] == null ? undefined : json['averageLoadPenalty'],
    };
}

export function CacheStatInfoToJSON(json: any): CacheStatInfo {
    return CacheStatInfoToJSONTyped(json, false);
}

export function CacheStatInfoToJSONTyped(value?: CacheStatInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hitRate': value['hitRate'],
        'missRate': value['missRate'],
        'hitCount': value['hitCount'],
        'missCount': value['missCount'],
        'loadCount': value['loadCount'],
        'evictionCount': value['evictionCount'],
        'averageLoadPenalty': value['averageLoadPenalty'],
    };
}

