/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CacheStatInfo
 */
export interface CacheStatInfo {
    /**
     * 
     * @type {number}
     * @memberof CacheStatInfo
     */
    hitRate: number;
    /**
     * 
     * @type {number}
     * @memberof CacheStatInfo
     */
    missRate: number;
    /**
     * 
     * @type {number}
     * @memberof CacheStatInfo
     */
    hitCount: number;
    /**
     * 
     * @type {number}
     * @memberof CacheStatInfo
     */
    missCount: number;
    /**
     * 
     * @type {number}
     * @memberof CacheStatInfo
     */
    loadCount: number;
    /**
     * 
     * @type {number}
     * @memberof CacheStatInfo
     */
    evictionCount: number;
    /**
     * 
     * @type {number}
     * @memberof CacheStatInfo
     */
    averageLoadPenalty: number;
}

/**
 * Check if a given object implements the CacheStatInfo interface.
 */
export function instanceOfCacheStatInfo(value: object): value is CacheStatInfo {
    if ((!('hitRate' in value) && !('hit_rate' in value)) || (value['hitRate'] === undefined && value['hit_rate'] === undefined)) return false;
    if ((!('missRate' in value) && !('miss_rate' in value)) || (value['missRate'] === undefined && value['miss_rate'] === undefined)) return false;
    if ((!('hitCount' in value) && !('hit_count' in value)) || (value['hitCount'] === undefined && value['hit_count'] === undefined)) return false;
    if ((!('missCount' in value) && !('miss_count' in value)) || (value['missCount'] === undefined && value['miss_count'] === undefined)) return false;
    if ((!('loadCount' in value) && !('load_count' in value)) || (value['loadCount'] === undefined && value['load_count'] === undefined)) return false;
    if ((!('evictionCount' in value) && !('eviction_count' in value)) || (value['evictionCount'] === undefined && value['eviction_count'] === undefined)) return false;
    if ((!('averageLoadPenalty' in value) && !('average_load_penalty' in value)) || (value['averageLoadPenalty'] === undefined && value['average_load_penalty'] === undefined)) return false;
    return true;
}

export function CacheStatInfoFromJSON(json: any): CacheStatInfo {
    return CacheStatInfoFromJSONTyped(json, false);
}

export function CacheStatInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheStatInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'hitRate': json['hit_rate'],
        'missRate': json['miss_rate'],
        'hitCount': json['hit_count'],
        'missCount': json['miss_count'],
        'loadCount': json['load_count'],
        'evictionCount': json['eviction_count'],
        'averageLoadPenalty': json['average_load_penalty'],
    };
}

export function CacheStatInfoToJSON(json: any): CacheStatInfo {
    return CacheStatInfoToJSONTyped(json, false);
}

export function CacheStatInfoToJSONTyped(value?: CacheStatInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hit_rate': value['hitRate'],
        'miss_rate': value['missRate'],
        'hit_count': value['hitCount'],
        'miss_count': value['missCount'],
        'load_count': value['loadCount'],
        'eviction_count': value['evictionCount'],
        'average_load_penalty': value['averageLoadPenalty'],
    };
}

