/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentsAddDTO
 */
export interface CommentsAddDTO {
    /**
     * 评论内容
     *  500字长度为对作者的限制，对于非作者限制为150字
     *  在业务层中实现
     * @type {string}
     * @memberof CommentsAddDTO
     */
    message: string;
    /**
     * 评论所在作业的 id
     * @type {number}
     * @memberof CommentsAddDTO
     */
    copilotId?: number;
    /**
     * 被回复评论的 id
     * @type {number}
     * @memberof CommentsAddDTO
     */
    fromCommentId?: number | null;
    /**
     * 是否接收通知
     * @type {boolean}
     * @memberof CommentsAddDTO
     */
    notification?: boolean;
    /**
     * 是否允许评论
     * @type {CommentsAddDTOCommentStatusEnum}
     * @memberof CommentsAddDTO
     */
    commentStatus?: CommentsAddDTOCommentStatusEnum;
}


/**
 * @export
 */
export const CommentsAddDTOCommentStatusEnum = {
    Enabled: 'ENABLED',
    Disabled: 'DISABLED'
} as const;
export type CommentsAddDTOCommentStatusEnum = typeof CommentsAddDTOCommentStatusEnum[keyof typeof CommentsAddDTOCommentStatusEnum];


/**
 * Check if a given object implements the CommentsAddDTO interface.
 */
export function instanceOfCommentsAddDTO(value: object): value is CommentsAddDTO {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CommentsAddDTOFromJSON(json: any): CommentsAddDTO {
    return CommentsAddDTOFromJSONTyped(json, false);
}

export function CommentsAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentsAddDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'copilotId': json['copilotId'] == null ? undefined : json['copilotId'],
        'fromCommentId': json['fromCommentId'] == null ? undefined : json['fromCommentId'],
        'notification': json['notification'] == null ? undefined : json['notification'],
        'commentStatus': json['commentStatus'] == null ? undefined : json['commentStatus'],
    };
}

export function CommentsAddDTOToJSON(json: any): CommentsAddDTO {
    return CommentsAddDTOToJSONTyped(json, false);
}

export function CommentsAddDTOToJSONTyped(value?: CommentsAddDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'copilotId': value['copilotId'],
        'fromCommentId': value['fromCommentId'],
        'notification': value['notification'],
        'commentStatus': value['commentStatus'],
    };
}

