/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommentsInfo } from './CommentsInfo';
import {
    CommentsInfoFromJSON,
    CommentsInfoFromJSONTyped,
    CommentsInfoToJSON,
    CommentsInfoToJSONTyped,
} from './CommentsInfo';

/**
 * 
 * @export
 * @interface CommentsAreaInfo
 */
export interface CommentsAreaInfo {
    /**
     * 
     * @type {boolean}
     * @memberof CommentsAreaInfo
     */
    hasNext?: boolean;
    /**
     * Total number of pages
     * @type {number}
     * @memberof CommentsAreaInfo
     */
    page?: number;
    /**
     * Total number of elements
     * @type {number}
     * @memberof CommentsAreaInfo
     */
    total?: number;
    /**
     * 
     * @type {Array<CommentsInfo>}
     * @memberof CommentsAreaInfo
     */
    data?: Array<CommentsInfo>;
}

/**
 * Check if a given object implements the CommentsAreaInfo interface.
 */
export function instanceOfCommentsAreaInfo(value: object): value is CommentsAreaInfo {
    return true;
}

export function CommentsAreaInfoFromJSON(json: any): CommentsAreaInfo {
    return CommentsAreaInfoFromJSONTyped(json, false);
}

export function CommentsAreaInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentsAreaInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'hasNext': json['hasNext'] == null ? undefined : json['hasNext'],
        'page': json['page'] == null ? undefined : json['page'],
        'total': json['total'] == null ? undefined : json['total'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(CommentsInfoFromJSON)),
    };
}

export function CommentsAreaInfoToJSON(json: any): CommentsAreaInfo {
    return CommentsAreaInfoToJSONTyped(json, false);
}

export function CommentsAreaInfoToJSONTyped(value?: CommentsAreaInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hasNext': value['hasNext'],
        'page': value['page'],
        'total': value['total'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(CommentsInfoToJSON)),
    };
}

