/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentsDeleteDTO
 */
export interface CommentsDeleteDTO {
    /**
     * 
     * @type {string}
     * @memberof CommentsDeleteDTO
     */
    commentId: string;
}

/**
 * Check if a given object implements the CommentsDeleteDTO interface.
 */
export function instanceOfCommentsDeleteDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "commentId" in value;

    return isInstance;
}

export function CommentsDeleteDTOFromJSON(json: any): CommentsDeleteDTO {
    return CommentsDeleteDTOFromJSONTyped(json, false);
}

export function CommentsDeleteDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentsDeleteDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'commentId': json['comment_id'],
    };
}

export function CommentsDeleteDTOToJSON(value?: CommentsDeleteDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'comment_id': value.commentId,
    };
}

