/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubCommentsInfo } from './SubCommentsInfo';
import {
    SubCommentsInfoFromJSON,
    SubCommentsInfoFromJSONTyped,
    SubCommentsInfoToJSON,
    SubCommentsInfoToJSONTyped,
} from './SubCommentsInfo';

/**
 * 
 * @export
 * @interface CommentsInfo
 */
export interface CommentsInfo {
    /**
     * 
     * @type {number}
     * @memberof CommentsInfo
     */
    commentId?: number;
    /**
     * 
     * @type {string}
     * @memberof CommentsInfo
     */
    uploader?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentsInfo
     */
    uploaderId?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentsInfo
     */
    message?: string;
    /**
     * 
     * @type {Date}
     * @memberof CommentsInfo
     */
    uploadTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof CommentsInfo
     */
    like?: number;
    /**
     * 
     * @type {number}
     * @memberof CommentsInfo
     */
    dislike?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CommentsInfo
     */
    topping?: boolean;
    /**
     * 
     * @type {Array<SubCommentsInfo>}
     * @memberof CommentsInfo
     */
    subCommentsInfos?: Array<SubCommentsInfo>;
}

/**
 * Check if a given object implements the CommentsInfo interface.
 */
export function instanceOfCommentsInfo(value: object): value is CommentsInfo {
    return true;
}

export function CommentsInfoFromJSON(json: any): CommentsInfo {
    return CommentsInfoFromJSONTyped(json, false);
}

export function CommentsInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentsInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'commentId': json['commentId'] == null ? undefined : json['commentId'],
        'uploader': json['uploader'] == null ? undefined : json['uploader'],
        'uploaderId': json['uploaderId'] == null ? undefined : json['uploaderId'],
        'message': json['message'] == null ? undefined : json['message'],
        'uploadTime': json['uploadTime'] == null ? undefined : (new Date(json['uploadTime'])),
        'like': json['like'] == null ? undefined : json['like'],
        'dislike': json['dislike'] == null ? undefined : json['dislike'],
        'topping': json['topping'] == null ? undefined : json['topping'],
        'subCommentsInfos': json['subCommentsInfos'] == null ? undefined : ((json['subCommentsInfos'] as Array<any>).map(SubCommentsInfoFromJSON)),
    };
}

export function CommentsInfoToJSON(json: any): CommentsInfo {
    return CommentsInfoToJSONTyped(json, false);
}

export function CommentsInfoToJSONTyped(value?: CommentsInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'commentId': value['commentId'],
        'uploader': value['uploader'],
        'uploaderId': value['uploaderId'],
        'message': value['message'],
        'uploadTime': value['uploadTime'] == null ? value['uploadTime'] : value['uploadTime'].toISOString(),
        'like': value['like'],
        'dislike': value['dislike'],
        'topping': value['topping'],
        'subCommentsInfos': value['subCommentsInfos'] == null ? undefined : ((value['subCommentsInfos'] as Array<any>).map(SubCommentsInfoToJSON)),
    };
}

