/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommentsInfo } from './CommentsInfo';
import {
    CommentsInfoFromJSON,
    CommentsInfoFromJSONTyped,
    CommentsInfoToJSON,
    CommentsInfoToJSONTyped,
} from './CommentsInfo';

/**
 * 
 * @export
 * @interface CommentsAreaInfo
 */
export interface CommentsAreaInfo {
    /**
     * 
     * @type {boolean}
     * @memberof CommentsAreaInfo
     */
    hasNext: boolean;
    /**
     * 
     * @type {number}
     * @memberof CommentsAreaInfo
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof CommentsAreaInfo
     */
    total: number;
    /**
     * 
     * @type {Array<CommentsInfo>}
     * @memberof CommentsAreaInfo
     */
    data: Array<CommentsInfo>;
}

/**
 * Check if a given object implements the CommentsAreaInfo interface.
 */
export function instanceOfCommentsAreaInfo(value: object): value is CommentsAreaInfo {
    if (!('hasNext' in value) || value['hasNext'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CommentsAreaInfoFromJSON(json: any): CommentsAreaInfo {
    return CommentsAreaInfoFromJSONTyped(json, false);
}

export function CommentsAreaInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentsAreaInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'hasNext': json['has_next'],
        'page': json['page'],
        'total': json['total'],
        'data': ((json['data'] as Array<any>).map(CommentsInfoFromJSON)),
    };
}

export function CommentsAreaInfoToJSON(json: any): CommentsAreaInfo {
    return CommentsAreaInfoToJSONTyped(json, false);
}

export function CommentsAreaInfoToJSONTyped(value?: CommentsAreaInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'has_next': value['hasNext'],
        'page': value['page'],
        'total': value['total'],
        'data': ((value['data'] as Array<any>).map(CommentsInfoToJSON)),
    };
}

