/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommonIdReqLong
 */
export interface CommonIdReqLong {
    /**
     * 
     * @type {number}
     * @memberof CommonIdReqLong
     */
    id: number;
}

/**
 * Check if a given object implements the CommonIdReqLong interface.
 */
export function instanceOfCommonIdReqLong(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function CommonIdReqLongFromJSON(json: any): CommonIdReqLong {
    return CommonIdReqLongFromJSONTyped(json, false);
}

export function CommonIdReqLongFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonIdReqLong {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function CommonIdReqLongToJSON(value?: CommonIdReqLong | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

