/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentsDeleteDTO
 */
export interface CommentsDeleteDTO {
    /**
     * 
     * @type {string}
     * @memberof CommentsDeleteDTO
     */
    commentId: string;
}

/**
 * Check if a given object implements the CommentsDeleteDTO interface.
 */
export function instanceOfCommentsDeleteDTO(value: object): value is CommentsDeleteDTO {
    if (!('commentId' in value) || value['commentId'] === undefined) return false;
    return true;
}

export function CommentsDeleteDTOFromJSON(json: any): CommentsDeleteDTO {
    return CommentsDeleteDTOFromJSONTyped(json, false);
}

export function CommentsDeleteDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentsDeleteDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'commentId': json['comment_id'],
    };
}

  export function CommentsDeleteDTOToJSON(json: any): CommentsDeleteDTO {
      return CommentsDeleteDTOToJSONTyped(json, false);
  }

  export function CommentsDeleteDTOToJSONTyped(value?: CommentsDeleteDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comment_id': value['commentId'],
    };
}

