/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CopilotInfo } from './CopilotInfo';
import {
    CopilotInfoFromJSON,
    CopilotInfoFromJSONTyped,
    CopilotInfoToJSON,
} from './CopilotInfo';

/**
 * 
 * @export
 * @interface CopilotPageInfo
 */
export interface CopilotPageInfo {
    /**
     * 
     * @type {boolean}
     * @memberof CopilotPageInfo
     */
    hasNext: boolean;
    /**
     * 
     * @type {number}
     * @memberof CopilotPageInfo
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof CopilotPageInfo
     */
    total: number;
    /**
     * 
     * @type {Array<CopilotInfo>}
     * @memberof CopilotPageInfo
     */
    data: Array<CopilotInfo>;
}

/**
 * Check if a given object implements the CopilotPageInfo interface.
 */
export function instanceOfCopilotPageInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "hasNext" in value;
    isInstance = isInstance && "page" in value;
    isInstance = isInstance && "total" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function CopilotPageInfoFromJSON(json: any): CopilotPageInfo {
    return CopilotPageInfoFromJSONTyped(json, false);
}

export function CopilotPageInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CopilotPageInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hasNext': json['has_next'],
        'page': json['page'],
        'total': json['total'],
        'data': ((json['data'] as Array<any>).map(CopilotInfoFromJSON)),
    };
}

export function CopilotPageInfoToJSON(value?: CopilotPageInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'has_next': value.hasNext,
        'page': value.page,
        'total': value.total,
        'data': ((value.data as Array<any>).map(CopilotInfoToJSON)),
    };
}

