/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CopilotSetListRes } from './CopilotSetListRes';
import {
    CopilotSetListResFromJSON,
    CopilotSetListResFromJSONTyped,
    CopilotSetListResToJSON,
} from './CopilotSetListRes';

/**
 * 
 * @export
 * @interface CopilotSetPageRes
 */
export interface CopilotSetPageRes {
    /**
     * 
     * @type {boolean}
     * @memberof CopilotSetPageRes
     */
    hasNext: boolean;
    /**
     * 
     * @type {number}
     * @memberof CopilotSetPageRes
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof CopilotSetPageRes
     */
    total: number;
    /**
     * 
     * @type {Array<CopilotSetListRes>}
     * @memberof CopilotSetPageRes
     */
    data: Array<CopilotSetListRes>;
}

/**
 * Check if a given object implements the CopilotSetPageRes interface.
 */
export function instanceOfCopilotSetPageRes(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "hasNext" in value;
    isInstance = isInstance && "page" in value;
    isInstance = isInstance && "total" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function CopilotSetPageResFromJSON(json: any): CopilotSetPageRes {
    return CopilotSetPageResFromJSONTyped(json, false);
}

export function CopilotSetPageResFromJSONTyped(json: any, ignoreDiscriminator: boolean): CopilotSetPageRes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hasNext': json['has_next'],
        'page': json['page'],
        'total': json['total'],
        'data': ((json['data'] as Array<any>).map(CopilotSetListResFromJSON)),
    };
}

export function CopilotSetPageResToJSON(value?: CopilotSetPageRes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'has_next': value.hasNext,
        'page': value.page,
        'total': value.total,
        'data': ((value.data as Array<any>).map(CopilotSetListResToJSON)),
    };
}

