/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CopilotSetListRes } from './CopilotSetListRes';
import {
    CopilotSetListResFromJSON,
    CopilotSetListResFromJSONTyped,
    CopilotSetListResToJSON,
    CopilotSetListResToJSONTyped,
} from './CopilotSetListRes';

/**
 * 
 * @export
 * @interface CopilotSetPageRes
 */
export interface CopilotSetPageRes {
    /**
     * 
     * @type {boolean}
     * @memberof CopilotSetPageRes
     */
    hasNext: boolean;
    /**
     * 
     * @type {number}
     * @memberof CopilotSetPageRes
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof CopilotSetPageRes
     */
    total: number;
    /**
     * 
     * @type {Array<CopilotSetListRes>}
     * @memberof CopilotSetPageRes
     */
    data: Array<CopilotSetListRes>;
}

/**
 * Check if a given object implements the CopilotSetPageRes interface.
 */
export function instanceOfCopilotSetPageRes(value: object): value is CopilotSetPageRes {
    if (!('hasNext' in value) || value['hasNext'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CopilotSetPageResFromJSON(json: any): CopilotSetPageRes {
    return CopilotSetPageResFromJSONTyped(json, false);
}

export function CopilotSetPageResFromJSONTyped(json: any, ignoreDiscriminator: boolean): CopilotSetPageRes {
    if (json == null) {
        return json;
    }
    return {
        
        'hasNext': json['has_next'],
        'page': json['page'],
        'total': json['total'],
        'data': ((json['data'] as Array<any>).map(CopilotSetListResFromJSON)),
    };
}

export function CopilotSetPageResToJSON(json: any): CopilotSetPageRes {
    return CopilotSetPageResToJSONTyped(json, false);
}

export function CopilotSetPageResToJSONTyped(value?: CopilotSetPageRes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'has_next': value['hasNext'],
        'page': value['page'],
        'total': value['total'],
        'data': ((value['data'] as Array<any>).map(CopilotSetListResToJSON)),
    };
}

