/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CopilotCUDRequest
 */
export interface CopilotCUDRequest {
    /**
     * 
     * @type {string}
     * @memberof CopilotCUDRequest
     */
    content?: string;
    /**
     * 
     * @type {number}
     * @memberof CopilotCUDRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the CopilotCUDRequest interface.
 */
export function instanceOfCopilotCUDRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CopilotCUDRequestFromJSON(json: any): CopilotCUDRequest {
    return CopilotCUDRequestFromJSONTyped(json, false);
}

export function CopilotCUDRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CopilotCUDRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'content': !exists(json, 'content') ? undefined : json['content'],
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function CopilotCUDRequestToJSON(value?: CopilotCUDRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': value.content,
        'id': value.id,
    };
}

