/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CopilotSetQuery
 */
export interface CopilotSetQuery {
    /**
     * 
     * @type {number}
     * @memberof CopilotSetQuery
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof CopilotSetQuery
     */
    limit?: number;
    /**
     * 
     * @type {string}
     * @memberof CopilotSetQuery
     */
    keyword?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CopilotSetQuery
     */
    creatorId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CopilotSetQuery
     */
    onlyFollowing?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof CopilotSetQuery
     */
    copilotIds?: Array<number> | null;
    /**
     * 
     * @type {boolean}
     * @memberof CopilotSetQuery
     */
    desc?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CopilotSetQuery
     */
    orderBy?: string | null;
}

/**
 * Check if a given object implements the CopilotSetQuery interface.
 */
export function instanceOfCopilotSetQuery(value: object): value is CopilotSetQuery {
    return true;
}

export function CopilotSetQueryFromJSON(json: any): CopilotSetQuery {
    return CopilotSetQueryFromJSONTyped(json, false);
}

export function CopilotSetQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CopilotSetQuery {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'keyword': json['keyword'] == null ? undefined : json['keyword'],
        'creatorId': json['creatorId'] == null ? undefined : json['creatorId'],
        'onlyFollowing': json['onlyFollowing'] == null ? undefined : json['onlyFollowing'],
        'copilotIds': json['copilotIds'] == null ? undefined : json['copilotIds'],
        'desc': json['desc'] == null ? undefined : json['desc'],
        'orderBy': json['orderBy'] == null ? undefined : json['orderBy'],
    };
}

export function CopilotSetQueryToJSON(json: any): CopilotSetQuery {
    return CopilotSetQueryToJSONTyped(json, false);
}

export function CopilotSetQueryToJSONTyped(value?: CopilotSetQuery | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'limit': value['limit'],
        'keyword': value['keyword'],
        'creatorId': value['creatorId'],
        'onlyFollowing': value['onlyFollowing'],
        'copilotIds': value['copilotIds'],
        'desc': value['desc'],
        'orderBy': value['orderBy'],
    };
}

