/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 作业/作业集的公开程度
 *  命名失误，已经改不了嘞
 * @export
 */
export const CopilotSetStatus = {
    Private: 'PRIVATE',
    Public: 'PUBLIC'
} as const;
export type CopilotSetStatus = typeof CopilotSetStatus[keyof typeof CopilotSetStatus];


export function instanceOfCopilotSetStatus(value: any): boolean {
    for (const key in CopilotSetStatus) {
        if (Object.prototype.hasOwnProperty.call(CopilotSetStatus, key)) {
            if (CopilotSetStatus[key as keyof typeof CopilotSetStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CopilotSetStatusFromJSON(json: any): CopilotSetStatus {
    return CopilotSetStatusFromJSONTyped(json, false);
}

export function CopilotSetStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CopilotSetStatus {
    return json as CopilotSetStatus;
}

export function CopilotSetStatusToJSON(value?: CopilotSetStatus | null): any {
    return value as any;
}

export function CopilotSetStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): CopilotSetStatus {
    return value as CopilotSetStatus;
}

