/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CopilotSetStatus } from './CopilotSetStatus';
import {
    CopilotSetStatusFromJSON,
    CopilotSetStatusFromJSONTyped,
    CopilotSetStatusToJSON,
    CopilotSetStatusToJSONTyped,
} from './CopilotSetStatus';

/**
 * 
 * @export
 * @interface CopilotSetUpdateReq
 */
export interface CopilotSetUpdateReq {
    /**
     * 
     * @type {number}
     * @memberof CopilotSetUpdateReq
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof CopilotSetUpdateReq
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CopilotSetUpdateReq
     */
    description?: string;
    /**
     * 
     * @type {CopilotSetStatus}
     * @memberof CopilotSetUpdateReq
     */
    status?: CopilotSetStatus;
    /**
     * 
     * @type {Array<number>}
     * @memberof CopilotSetUpdateReq
     */
    copilotIds?: Array<number>;
}



/**
 * Check if a given object implements the CopilotSetUpdateReq interface.
 */
export function instanceOfCopilotSetUpdateReq(value: object): value is CopilotSetUpdateReq {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CopilotSetUpdateReqFromJSON(json: any): CopilotSetUpdateReq {
    return CopilotSetUpdateReqFromJSONTyped(json, false);
}

export function CopilotSetUpdateReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): CopilotSetUpdateReq {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'] == null ? undefined : CopilotSetStatusFromJSON(json['status']),
        'copilotIds': json['copilot_ids'] == null ? undefined : json['copilot_ids'],
    };
}

export function CopilotSetUpdateReqToJSON(json: any): CopilotSetUpdateReq {
    return CopilotSetUpdateReqToJSONTyped(json, false);
}

export function CopilotSetUpdateReqToJSONTyped(value?: CopilotSetUpdateReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'status': CopilotSetStatusToJSON(value['status']),
        'copilot_ids': value['copilotIds'],
    };
}

