/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CopilotSetStatus } from './CopilotSetStatus';
import {
    CopilotSetStatusFromJSON,
    CopilotSetStatusFromJSONTyped,
    CopilotSetStatusToJSON,
} from './CopilotSetStatus';

/**
 * 
 * @export
 * @interface CopilotSetCreateReq
 */
export interface CopilotSetCreateReq {
    /**
     * 
     * @type {string}
     * @memberof CopilotSetCreateReq
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CopilotSetCreateReq
     */
    description: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof CopilotSetCreateReq
     */
    copilotIds: Array<number>;
    /**
     * 
     * @type {CopilotSetStatus}
     * @memberof CopilotSetCreateReq
     */
    status: CopilotSetStatus;
}

/**
 * Check if a given object implements the CopilotSetCreateReq interface.
 */
export function instanceOfCopilotSetCreateReq(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "copilotIds" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function CopilotSetCreateReqFromJSON(json: any): CopilotSetCreateReq {
    return CopilotSetCreateReqFromJSONTyped(json, false);
}

export function CopilotSetCreateReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): CopilotSetCreateReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'copilotIds': json['copilot_ids'],
        'status': CopilotSetStatusFromJSON(json['status']),
    };
}

export function CopilotSetCreateReqToJSON(value?: CopilotSetCreateReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'copilot_ids': value.copilotIds,
        'status': CopilotSetStatusToJSON(value.status),
    };
}

