/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CopilotSetStatus } from './CopilotSetStatus';
import {
    CopilotSetStatusFromJSON,
    CopilotSetStatusFromJSONTyped,
    CopilotSetStatusToJSON,
    CopilotSetStatusToJSONTyped,
} from './CopilotSetStatus';

/**
 * 
 * @export
 * @interface CopilotInfo
 */
export interface CopilotInfo {
    /**
     * 
     * @type {number}
     * @memberof CopilotInfo
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof CopilotInfo
     */
    uploadTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof CopilotInfo
     */
    uploaderId?: string;
    /**
     * 
     * @type {string}
     * @memberof CopilotInfo
     */
    uploader?: string;
    /**
     * 
     * @type {number}
     * @memberof CopilotInfo
     */
    views?: number;
    /**
     * 
     * @type {number}
     * @memberof CopilotInfo
     */
    hotScore?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CopilotInfo
     */
    available?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CopilotInfo
     */
    ratingLevel?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CopilotInfo
     */
    notEnoughRating?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CopilotInfo
     */
    ratingRatio?: number;
    /**
     * 
     * @type {number}
     * @memberof CopilotInfo
     */
    ratingType?: number;
    /**
     * 
     * @type {number}
     * @memberof CopilotInfo
     */
    commentsCount?: number;
    /**
     * 
     * @type {string}
     * @memberof CopilotInfo
     */
    content?: string;
    /**
     * 
     * @type {number}
     * @memberof CopilotInfo
     */
    like?: number;
    /**
     * 
     * @type {number}
     * @memberof CopilotInfo
     */
    dislike?: number;
    /**
     * 
     * @type {CopilotInfoCommentStatusEnum}
     * @memberof CopilotInfo
     */
    commentStatus?: CopilotInfoCommentStatusEnum;
    /**
     * 
     * @type {CopilotSetStatus}
     * @memberof CopilotInfo
     */
    status?: CopilotSetStatus;
}


/**
 * @export
 */
export const CopilotInfoCommentStatusEnum = {
    Enabled: 'ENABLED',
    Disabled: 'DISABLED'
} as const;
export type CopilotInfoCommentStatusEnum = typeof CopilotInfoCommentStatusEnum[keyof typeof CopilotInfoCommentStatusEnum];


/**
 * Check if a given object implements the CopilotInfo interface.
 */
export function instanceOfCopilotInfo(value: object): value is CopilotInfo {
    return true;
}

export function CopilotInfoFromJSON(json: any): CopilotInfo {
    return CopilotInfoFromJSONTyped(json, false);
}

export function CopilotInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CopilotInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'uploadTime': json['upload_time'] == null ? undefined : (new Date(json['upload_time'])),
        'uploaderId': json['uploader_id'] == null ? undefined : json['uploader_id'],
        'uploader': json['uploader'] == null ? undefined : json['uploader'],
        'views': json['views'] == null ? undefined : json['views'],
        'hotScore': json['hot_score'] == null ? undefined : json['hot_score'],
        'available': json['available'] == null ? undefined : json['available'],
        'ratingLevel': json['rating_level'] == null ? undefined : json['rating_level'],
        'notEnoughRating': json['not_enough_rating'] == null ? undefined : json['not_enough_rating'],
        'ratingRatio': json['rating_ratio'] == null ? undefined : json['rating_ratio'],
        'ratingType': json['rating_type'] == null ? undefined : json['rating_type'],
        'commentsCount': json['comments_count'] == null ? undefined : json['comments_count'],
        'content': json['content'] == null ? undefined : json['content'],
        'like': json['like'] == null ? undefined : json['like'],
        'dislike': json['dislike'] == null ? undefined : json['dislike'],
        'commentStatus': json['comment_status'] == null ? undefined : json['comment_status'],
        'status': json['status'] == null ? undefined : CopilotSetStatusFromJSON(json['status']),
    };
}

export function CopilotInfoToJSON(json: any): CopilotInfo {
    return CopilotInfoToJSONTyped(json, false);
}

export function CopilotInfoToJSONTyped(value?: CopilotInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'upload_time': value['uploadTime'] == null ? value['uploadTime'] : value['uploadTime'].toISOString(),
        'uploader_id': value['uploaderId'],
        'uploader': value['uploader'],
        'views': value['views'],
        'hot_score': value['hotScore'],
        'available': value['available'],
        'rating_level': value['ratingLevel'],
        'not_enough_rating': value['notEnoughRating'],
        'rating_ratio': value['ratingRatio'],
        'rating_type': value['ratingType'],
        'comments_count': value['commentsCount'],
        'content': value['content'],
        'like': value['like'],
        'dislike': value['dislike'],
        'comment_status': value['commentStatus'],
        'status': CopilotSetStatusToJSON(value['status']),
    };
}

