/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CopilotSetStatus } from './CopilotSetStatus';
import {
    CopilotSetStatusFromJSON,
    CopilotSetStatusFromJSONTyped,
    CopilotSetStatusToJSON,
    CopilotSetStatusToJSONTyped,
} from './CopilotSetStatus';

/**
 * 
 * @export
 * @interface CopilotInfo
 */
export interface CopilotInfo {
    /**
     * 
     * @type {number}
     * @memberof CopilotInfo
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof CopilotInfo
     */
    uploadTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof CopilotInfo
     */
    uploaderId?: string;
    /**
     * 
     * @type {string}
     * @memberof CopilotInfo
     */
    uploader?: string;
    /**
     * 
     * @type {number}
     * @memberof CopilotInfo
     */
    views?: number;
    /**
     * 
     * @type {number}
     * @memberof CopilotInfo
     */
    hotScore?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CopilotInfo
     */
    available?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CopilotInfo
     */
    ratingLevel?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CopilotInfo
     */
    notEnoughRating?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CopilotInfo
     */
    ratingRatio?: number;
    /**
     * 
     * @type {number}
     * @memberof CopilotInfo
     */
    ratingType?: number;
    /**
     * 
     * @type {number}
     * @memberof CopilotInfo
     */
    commentsCount?: number;
    /**
     * 
     * @type {string}
     * @memberof CopilotInfo
     */
    content?: string;
    /**
     * 
     * @type {number}
     * @memberof CopilotInfo
     */
    like?: number;
    /**
     * 
     * @type {number}
     * @memberof CopilotInfo
     */
    dislike?: number;
    /**
     * 
     * @type {CopilotInfoCommentStatusEnum}
     * @memberof CopilotInfo
     */
    commentStatus?: CopilotInfoCommentStatusEnum;
    /**
     * 
     * @type {CopilotSetStatus}
     * @memberof CopilotInfo
     */
    status?: CopilotSetStatus;
}


/**
 * @export
 */
export const CopilotInfoCommentStatusEnum = {
    Enabled: 'ENABLED',
    Disabled: 'DISABLED'
} as const;
export type CopilotInfoCommentStatusEnum = typeof CopilotInfoCommentStatusEnum[keyof typeof CopilotInfoCommentStatusEnum];


/**
 * Check if a given object implements the CopilotInfo interface.
 */
export function instanceOfCopilotInfo(value: object): value is CopilotInfo {
    return true;
}

export function CopilotInfoFromJSON(json: any): CopilotInfo {
    return CopilotInfoFromJSONTyped(json, false);
}

export function CopilotInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CopilotInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'uploadTime': json['uploadTime'] == null ? undefined : (new Date(json['uploadTime'])),
        'uploaderId': json['uploaderId'] == null ? undefined : json['uploaderId'],
        'uploader': json['uploader'] == null ? undefined : json['uploader'],
        'views': json['views'] == null ? undefined : json['views'],
        'hotScore': json['hotScore'] == null ? undefined : json['hotScore'],
        'available': json['available'] == null ? undefined : json['available'],
        'ratingLevel': json['ratingLevel'] == null ? undefined : json['ratingLevel'],
        'notEnoughRating': json['notEnoughRating'] == null ? undefined : json['notEnoughRating'],
        'ratingRatio': json['ratingRatio'] == null ? undefined : json['ratingRatio'],
        'ratingType': json['ratingType'] == null ? undefined : json['ratingType'],
        'commentsCount': json['commentsCount'] == null ? undefined : json['commentsCount'],
        'content': json['content'] == null ? undefined : json['content'],
        'like': json['like'] == null ? undefined : json['like'],
        'dislike': json['dislike'] == null ? undefined : json['dislike'],
        'commentStatus': json['commentStatus'] == null ? undefined : json['commentStatus'],
        'status': json['status'] == null ? undefined : CopilotSetStatusFromJSON(json['status']),
    };
}

export function CopilotInfoToJSON(json: any): CopilotInfo {
    return CopilotInfoToJSONTyped(json, false);
}

export function CopilotInfoToJSONTyped(value?: CopilotInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'uploadTime': value['uploadTime'] == null ? value['uploadTime'] : value['uploadTime'].toISOString(),
        'uploaderId': value['uploaderId'],
        'uploader': value['uploader'],
        'views': value['views'],
        'hotScore': value['hotScore'],
        'available': value['available'],
        'ratingLevel': value['ratingLevel'],
        'notEnoughRating': value['notEnoughRating'],
        'ratingRatio': value['ratingRatio'],
        'ratingType': value['ratingType'],
        'commentsCount': value['commentsCount'],
        'content': value['content'],
        'like': value['like'],
        'dislike': value['dislike'],
        'commentStatus': value['commentStatus'],
        'status': CopilotSetStatusToJSON(value['status']),
    };
}

