/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GitInfo
 */
export interface GitInfo {
    /**
     * 
     * @type {string}
     * @memberof GitInfo
     */
    branch?: string;
    /**
     * 
     * @type {string}
     * @memberof GitInfo
     */
    commitId?: string;
    /**
     * 
     * @type {string}
     * @memberof GitInfo
     */
    shortCommitId?: string;
    /**
     * 
     * @type {Date}
     * @memberof GitInfo
     */
    commitTime?: Date;
}

/**
 * Check if a given object implements the GitInfo interface.
 */
export function instanceOfGitInfo(value: object): value is GitInfo {
    return true;
}

export function GitInfoFromJSON(json: any): GitInfo {
    return GitInfoFromJSONTyped(json, false);
}

export function GitInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GitInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'branch': json['branch'] == null ? undefined : json['branch'],
        'commitId': json['commit_id'] == null ? undefined : json['commit_id'],
        'shortCommitId': json['short_commit_id'] == null ? undefined : json['short_commit_id'],
        'commitTime': json['commit_time'] == null ? undefined : (new Date(json['commit_time'])),
    };
}

export function GitInfoToJSON(json: any): GitInfo {
    return GitInfoToJSONTyped(json, false);
}

export function GitInfoToJSONTyped(value?: GitInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'branch': value['branch'],
        'commit_id': value['commitId'],
        'short_commit_id': value['shortCommitId'],
        'commit_time': value['commitTime'] == null ? value['commitTime'] : value['commitTime'].toISOString(),
    };
}

