/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GitProperties
 */
export interface GitProperties {
    /**
     * 
     * @type {string}
     * @memberof GitProperties
     */
    branch?: string;
    /**
     * 
     * @type {string}
     * @memberof GitProperties
     */
    shortCommitId?: string;
    /**
     * 
     * @type {Date}
     * @memberof GitProperties
     */
    commitTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof GitProperties
     */
    commitId?: string;
}

/**
 * Check if a given object implements the GitProperties interface.
 */
export function instanceOfGitProperties(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GitPropertiesFromJSON(json: any): GitProperties {
    return GitPropertiesFromJSONTyped(json, false);
}

export function GitPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GitProperties {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'branch': !exists(json, 'branch') ? undefined : json['branch'],
        'shortCommitId': !exists(json, 'short_commit_id') ? undefined : json['short_commit_id'],
        'commitTime': !exists(json, 'commit_time') ? undefined : (new Date(json['commit_time'])),
        'commitId': !exists(json, 'commit_id') ? undefined : json['commit_id'],
    };
}

export function GitPropertiesToJSON(value?: GitProperties | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'branch': value.branch,
        'short_commit_id': value.shortCommitId,
        'commit_time': value.commitTime === undefined ? undefined : (value.commitTime.toISOString()),
        'commit_id': value.commitId,
    };
}

