/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageDownloadDTO
 */
export interface ImageDownloadDTO {
    /**
     * 
     * @type {string}
     * @memberof ImageDownloadDTO
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ImageDownloadDTO
     */
    classification?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ImageDownloadDTO
     */
    version?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ImageDownloadDTO
     */
    label?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ImageDownloadDTO
     */
    _delete: boolean;
}

/**
 * Check if a given object implements the ImageDownloadDTO interface.
 */
export function instanceOfImageDownloadDTO(value: object): value is ImageDownloadDTO {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('_delete' in value) || value['_delete'] === undefined) return false;
    return true;
}

export function ImageDownloadDTOFromJSON(json: any): ImageDownloadDTO {
    return ImageDownloadDTOFromJSONTyped(json, false);
}

export function ImageDownloadDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageDownloadDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'classification': json['classification'] == null ? undefined : json['classification'],
        'version': json['version'] == null ? undefined : json['version'],
        'label': json['label'] == null ? undefined : json['label'],
        '_delete': json['delete'],
    };
}

export function ImageDownloadDTOToJSON(json: any): ImageDownloadDTO {
    return ImageDownloadDTOToJSONTyped(json, false);
}

export function ImageDownloadDTOToJSONTyped(value?: ImageDownloadDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'classification': value['classification'],
        'version': value['version'],
        'label': value['label'],
        'delete': value['_delete'],
    };
}

