/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * `/arknights/level/v2/version` 的响应体：一次往返拿到两个变体的当前版本号。
 * @export
 * @interface LevelVersions
 */
export interface LevelVersions {
    /**
     * 
     * @type {string}
     * @memberof LevelVersions
     */
    full: string;
    /**
     * 
     * @type {string}
     * @memberof LevelVersions
     */
    lite: string;
}

/**
 * Check if a given object implements the LevelVersions interface.
 */
export function instanceOfLevelVersions(value: object): value is LevelVersions {
    if (!('full' in value) || value['full'] === undefined) return false;
    if (!('lite' in value) || value['lite'] === undefined) return false;
    return true;
}

export function LevelVersionsFromJSON(json: any): LevelVersions {
    return LevelVersionsFromJSONTyped(json, false);
}

export function LevelVersionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LevelVersions {
    if (json == null) {
        return json;
    }
    return {
        
        'full': json['full'],
        'lite': json['lite'],
    };
}

export function LevelVersionsToJSON(json: any): LevelVersions {
    return LevelVersionsToJSONTyped(json, false);
}

export function LevelVersionsToJSONTyped(value?: LevelVersions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'full': value['full'],
        'lite': value['lite'],
    };
}

