/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MaaUserInfo } from './MaaUserInfo';
import {
    MaaUserInfoFromJSON,
    MaaUserInfoFromJSONTyped,
    MaaUserInfoToJSON,
    MaaUserInfoToJSONTyped,
} from './MaaUserInfo';

/**
 * 
 * @export
 * @interface MaaLoginRsp
 */
export interface MaaLoginRsp {
    /**
     * 
     * @type {string}
     * @memberof MaaLoginRsp
     */
    token?: string;
    /**
     * 
     * @type {Date}
     * @memberof MaaLoginRsp
     */
    validBefore?: Date;
    /**
     * 
     * @type {Date}
     * @memberof MaaLoginRsp
     */
    validAfter?: Date;
    /**
     * 
     * @type {string}
     * @memberof MaaLoginRsp
     */
    refreshToken?: string;
    /**
     * 
     * @type {Date}
     * @memberof MaaLoginRsp
     */
    refreshTokenValidBefore?: Date;
    /**
     * 
     * @type {Date}
     * @memberof MaaLoginRsp
     */
    refreshTokenValidAfter?: Date;
    /**
     * 
     * @type {MaaUserInfo}
     * @memberof MaaLoginRsp
     */
    userInfo?: MaaUserInfo;
}

/**
 * Check if a given object implements the MaaLoginRsp interface.
 */
export function instanceOfMaaLoginRsp(value: object): value is MaaLoginRsp {
    return true;
}

export function MaaLoginRspFromJSON(json: any): MaaLoginRsp {
    return MaaLoginRspFromJSONTyped(json, false);
}

export function MaaLoginRspFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaaLoginRsp {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
        'validBefore': json['valid_before'] == null ? undefined : (new Date(json['valid_before'])),
        'validAfter': json['valid_after'] == null ? undefined : (new Date(json['valid_after'])),
        'refreshToken': json['refresh_token'] == null ? undefined : json['refresh_token'],
        'refreshTokenValidBefore': json['refresh_token_valid_before'] == null ? undefined : (new Date(json['refresh_token_valid_before'])),
        'refreshTokenValidAfter': json['refresh_token_valid_after'] == null ? undefined : (new Date(json['refresh_token_valid_after'])),
        'userInfo': json['user_info'] == null ? undefined : MaaUserInfoFromJSON(json['user_info']),
    };
}

export function MaaLoginRspToJSON(json: any): MaaLoginRsp {
    return MaaLoginRspToJSONTyped(json, false);
}

export function MaaLoginRspToJSONTyped(value?: MaaLoginRsp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'valid_before': value['validBefore'] == null ? value['validBefore'] : value['validBefore'].toISOString(),
        'valid_after': value['validAfter'] == null ? value['validAfter'] : value['validAfter'].toISOString(),
        'refresh_token': value['refreshToken'],
        'refresh_token_valid_before': value['refreshTokenValidBefore'] == null ? value['refreshTokenValidBefore'] : value['refreshTokenValidBefore'].toISOString(),
        'refresh_token_valid_after': value['refreshTokenValidAfter'] == null ? value['refreshTokenValidAfter'] : value['refreshTokenValidAfter'].toISOString(),
        'user_info': MaaUserInfoToJSON(value['userInfo']),
    };
}

