/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MaaUserInfo } from './MaaUserInfo';
import {
    MaaUserInfoFromJSON,
    MaaUserInfoFromJSONTyped,
    MaaUserInfoToJSON,
} from './MaaUserInfo';

/**
 * 
 * @export
 * @interface MaaLoginRsp
 */
export interface MaaLoginRsp {
    /**
     * 
     * @type {string}
     * @memberof MaaLoginRsp
     */
    token: string;
    /**
     * 
     * @type {Date}
     * @memberof MaaLoginRsp
     */
    validBefore: Date;
    /**
     * 
     * @type {Date}
     * @memberof MaaLoginRsp
     */
    validAfter: Date;
    /**
     * 
     * @type {string}
     * @memberof MaaLoginRsp
     */
    refreshToken: string;
    /**
     * 
     * @type {Date}
     * @memberof MaaLoginRsp
     */
    refreshTokenValidBefore: Date;
    /**
     * 
     * @type {Date}
     * @memberof MaaLoginRsp
     */
    refreshTokenValidAfter: Date;
    /**
     * 
     * @type {MaaUserInfo}
     * @memberof MaaLoginRsp
     */
    userInfo: MaaUserInfo;
}

/**
 * Check if a given object implements the MaaLoginRsp interface.
 */
export function instanceOfMaaLoginRsp(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;
    isInstance = isInstance && "validBefore" in value;
    isInstance = isInstance && "validAfter" in value;
    isInstance = isInstance && "refreshToken" in value;
    isInstance = isInstance && "refreshTokenValidBefore" in value;
    isInstance = isInstance && "refreshTokenValidAfter" in value;
    isInstance = isInstance && "userInfo" in value;

    return isInstance;
}

export function MaaLoginRspFromJSON(json: any): MaaLoginRsp {
    return MaaLoginRspFromJSONTyped(json, false);
}

export function MaaLoginRspFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaaLoginRsp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
        'validBefore': (new Date(json['valid_before'])),
        'validAfter': (new Date(json['valid_after'])),
        'refreshToken': json['refresh_token'],
        'refreshTokenValidBefore': (new Date(json['refresh_token_valid_before'])),
        'refreshTokenValidAfter': (new Date(json['refresh_token_valid_after'])),
        'userInfo': MaaUserInfoFromJSON(json['user_info']),
    };
}

export function MaaLoginRspToJSON(value?: MaaLoginRsp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
        'valid_before': (value.validBefore.toISOString()),
        'valid_after': (value.validAfter.toISOString()),
        'refresh_token': value.refreshToken,
        'refresh_token_valid_before': (value.refreshTokenValidBefore.toISOString()),
        'refresh_token_valid_after': (value.refreshTokenValidAfter.toISOString()),
        'user_info': MaaUserInfoToJSON(value.userInfo),
    };
}

