/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MaaResultInteger
 */
export interface MaaResultInteger {
    /**
     * 
     * @type {number}
     * @memberof MaaResultInteger
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof MaaResultInteger
     */
    message?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MaaResultInteger
     */
    data?: number | null;
}

/**
 * Check if a given object implements the MaaResultInteger interface.
 */
export function instanceOfMaaResultInteger(value: object): value is MaaResultInteger {
    if ((!('statusCode' in value) && !('status_code' in value)) || (value['statusCode'] === undefined && value['status_code'] === undefined)) return false;
    return true;
}

export function MaaResultIntegerFromJSON(json: any): MaaResultInteger {
    return MaaResultIntegerFromJSONTyped(json, false);
}

export function MaaResultIntegerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaaResultInteger {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function MaaResultIntegerToJSON(json: any): MaaResultInteger {
    return MaaResultIntegerToJSONTyped(json, false);
}

export function MaaResultIntegerToJSONTyped(value?: MaaResultInteger | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'message': value['message'],
        'data': value['data'],
    };
}

