/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FollowStatusInfo } from './FollowStatusInfo';
import {
    FollowStatusInfoFromJSON,
    FollowStatusInfoFromJSONTyped,
    FollowStatusInfoToJSON,
    FollowStatusInfoToJSONTyped,
} from './FollowStatusInfo';

/**
 * 
 * @export
 * @interface MaaResultFollowStatusInfo
 */
export interface MaaResultFollowStatusInfo {
    /**
     * 
     * @type {number}
     * @memberof MaaResultFollowStatusInfo
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof MaaResultFollowStatusInfo
     */
    message?: string | null;
    /**
     * 
     * @type {FollowStatusInfo}
     * @memberof MaaResultFollowStatusInfo
     */
    data?: FollowStatusInfo | null;
}

/**
 * Check if a given object implements the MaaResultFollowStatusInfo interface.
 */
export function instanceOfMaaResultFollowStatusInfo(value: object): value is MaaResultFollowStatusInfo {
    if ((!('statusCode' in value) && !('status_code' in value)) || (value['statusCode'] === undefined && value['status_code'] === undefined)) return false;
    return true;
}

export function MaaResultFollowStatusInfoFromJSON(json: any): MaaResultFollowStatusInfo {
    return MaaResultFollowStatusInfoFromJSONTyped(json, false);
}

export function MaaResultFollowStatusInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaaResultFollowStatusInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : FollowStatusInfoFromJSON(json['data']),
    };
}

export function MaaResultFollowStatusInfoToJSON(json: any): MaaResultFollowStatusInfo {
    return MaaResultFollowStatusInfoToJSONTyped(json, false);
}

export function MaaResultFollowStatusInfoToJSONTyped(value?: MaaResultFollowStatusInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'message': value['message'],
        'data': FollowStatusInfoToJSON(value['data']),
    };
}

