/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MaaResultUnit
 */
export interface MaaResultUnit {
    /**
     * 
     * @type {number}
     * @memberof MaaResultUnit
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof MaaResultUnit
     */
    message?: string | null;
}

/**
 * Check if a given object implements the MaaResultUnit interface.
 */
export function instanceOfMaaResultUnit(value: object): value is MaaResultUnit {
    return true;
}

export function MaaResultUnitFromJSON(json: any): MaaResultUnit {
    return MaaResultUnitFromJSONTyped(json, false);
}

export function MaaResultUnitFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaaResultUnit {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function MaaResultUnitToJSON(json: any): MaaResultUnit {
    return MaaResultUnitToJSONTyped(json, false);
}

export function MaaResultUnitToJSONTyped(value?: MaaResultUnit | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
    };
}

