/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CopilotSetRes } from './CopilotSetRes';
import {
    CopilotSetResFromJSON,
    CopilotSetResFromJSONTyped,
    CopilotSetResToJSON,
    CopilotSetResToJSONTyped,
} from './CopilotSetRes';

/**
 * 
 * @export
 * @interface MaaResultCopilotSetRes
 */
export interface MaaResultCopilotSetRes {
    /**
     * 
     * @type {number}
     * @memberof MaaResultCopilotSetRes
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof MaaResultCopilotSetRes
     */
    message?: string;
    /**
     * 
     * @type {CopilotSetRes}
     * @memberof MaaResultCopilotSetRes
     */
    data?: CopilotSetRes;
}

/**
 * Check if a given object implements the MaaResultCopilotSetRes interface.
 */
export function instanceOfMaaResultCopilotSetRes(value: object): value is MaaResultCopilotSetRes {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function MaaResultCopilotSetResFromJSON(json: any): MaaResultCopilotSetRes {
    return MaaResultCopilotSetResFromJSONTyped(json, false);
}

export function MaaResultCopilotSetResFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaaResultCopilotSetRes {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : CopilotSetResFromJSON(json['data']),
    };
}

  export function MaaResultCopilotSetResToJSON(json: any): MaaResultCopilotSetRes {
      return MaaResultCopilotSetResToJSONTyped(json, false);
  }

  export function MaaResultCopilotSetResToJSONTyped(value?: MaaResultCopilotSetRes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'message': value['message'],
        'data': CopilotSetResToJSON(value['data']),
    };
}

