/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MaaSystemInfo } from './MaaSystemInfo';
import {
    MaaSystemInfoFromJSON,
    MaaSystemInfoFromJSONTyped,
    MaaSystemInfoToJSON,
} from './MaaSystemInfo';

/**
 * 
 * @export
 * @interface MaaResultMaaSystemInfo
 */
export interface MaaResultMaaSystemInfo {
    /**
     * 
     * @type {number}
     * @memberof MaaResultMaaSystemInfo
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof MaaResultMaaSystemInfo
     */
    message?: string;
    /**
     * 
     * @type {MaaSystemInfo}
     * @memberof MaaResultMaaSystemInfo
     */
    data?: MaaSystemInfo;
}

/**
 * Check if a given object implements the MaaResultMaaSystemInfo interface.
 */
export function instanceOfMaaResultMaaSystemInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "statusCode" in value;

    return isInstance;
}

export function MaaResultMaaSystemInfoFromJSON(json: any): MaaResultMaaSystemInfo {
    return MaaResultMaaSystemInfoFromJSONTyped(json, false);
}

export function MaaResultMaaSystemInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaaResultMaaSystemInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : MaaSystemInfoFromJSON(json['data']),
    };
}

export function MaaResultMaaSystemInfoToJSON(value?: MaaResultMaaSystemInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status_code': value.statusCode,
        'message': value.message,
        'data': MaaSystemInfoToJSON(value.data),
    };
}

