/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMaaUserInfo } from './PageMaaUserInfo';
import {
    PageMaaUserInfoFromJSON,
    PageMaaUserInfoFromJSONTyped,
    PageMaaUserInfoToJSON,
    PageMaaUserInfoToJSONTyped,
} from './PageMaaUserInfo';

/**
 * 
 * @export
 * @interface MaaResultPageMaaUserInfo
 */
export interface MaaResultPageMaaUserInfo {
    /**
     * 
     * @type {number}
     * @memberof MaaResultPageMaaUserInfo
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof MaaResultPageMaaUserInfo
     */
    message?: string;
    /**
     * 
     * @type {PageMaaUserInfo}
     * @memberof MaaResultPageMaaUserInfo
     */
    data?: PageMaaUserInfo;
}

/**
 * Check if a given object implements the MaaResultPageMaaUserInfo interface.
 */
export function instanceOfMaaResultPageMaaUserInfo(value: object): value is MaaResultPageMaaUserInfo {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function MaaResultPageMaaUserInfoFromJSON(json: any): MaaResultPageMaaUserInfo {
    return MaaResultPageMaaUserInfoFromJSONTyped(json, false);
}

export function MaaResultPageMaaUserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaaResultPageMaaUserInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : PageMaaUserInfoFromJSON(json['data']),
    };
}

export function MaaResultPageMaaUserInfoToJSON(json: any): MaaResultPageMaaUserInfo {
    return MaaResultPageMaaUserInfoToJSONTyped(json, false);
}

export function MaaResultPageMaaUserInfoToJSONTyped(value?: MaaResultPageMaaUserInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'message': value['message'],
        'data': PageMaaUserInfoToJSON(value['data']),
    };
}

