/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MaaLoginRsp } from './MaaLoginRsp';
import {
    MaaLoginRspFromJSON,
    MaaLoginRspFromJSONTyped,
    MaaLoginRspToJSON,
    MaaLoginRspToJSONTyped,
} from './MaaLoginRsp';

/**
 * 
 * @export
 * @interface MaaResultMaaLoginRsp
 */
export interface MaaResultMaaLoginRsp {
    /**
     * 
     * @type {number}
     * @memberof MaaResultMaaLoginRsp
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof MaaResultMaaLoginRsp
     */
    message?: string;
    /**
     * 
     * @type {MaaLoginRsp}
     * @memberof MaaResultMaaLoginRsp
     */
    data?: MaaLoginRsp;
}

/**
 * Check if a given object implements the MaaResultMaaLoginRsp interface.
 */
export function instanceOfMaaResultMaaLoginRsp(value: object): value is MaaResultMaaLoginRsp {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function MaaResultMaaLoginRspFromJSON(json: any): MaaResultMaaLoginRsp {
    return MaaResultMaaLoginRspFromJSONTyped(json, false);
}

export function MaaResultMaaLoginRspFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaaResultMaaLoginRsp {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : MaaLoginRspFromJSON(json['data']),
    };
}

export function MaaResultMaaLoginRspToJSON(json: any): MaaResultMaaLoginRsp {
    return MaaResultMaaLoginRspToJSONTyped(json, false);
}

export function MaaResultMaaLoginRspToJSONTyped(value?: MaaResultMaaLoginRsp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'message': value['message'],
        'data': MaaLoginRspToJSON(value['data']),
    };
}

