/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MaaSystemInfo } from './MaaSystemInfo';
import {
    MaaSystemInfoFromJSON,
    MaaSystemInfoFromJSONTyped,
    MaaSystemInfoToJSON,
    MaaSystemInfoToJSONTyped,
} from './MaaSystemInfo';

/**
 * 
 * @export
 * @interface MaaResultMaaSystemInfo
 */
export interface MaaResultMaaSystemInfo {
    /**
     * 
     * @type {number}
     * @memberof MaaResultMaaSystemInfo
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof MaaResultMaaSystemInfo
     */
    message?: string;
    /**
     * 
     * @type {MaaSystemInfo}
     * @memberof MaaResultMaaSystemInfo
     */
    data?: MaaSystemInfo;
}

/**
 * Check if a given object implements the MaaResultMaaSystemInfo interface.
 */
export function instanceOfMaaResultMaaSystemInfo(value: object): value is MaaResultMaaSystemInfo {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function MaaResultMaaSystemInfoFromJSON(json: any): MaaResultMaaSystemInfo {
    return MaaResultMaaSystemInfoFromJSONTyped(json, false);
}

export function MaaResultMaaSystemInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaaResultMaaSystemInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : MaaSystemInfoFromJSON(json['data']),
    };
}

  export function MaaResultMaaSystemInfoToJSON(json: any): MaaResultMaaSystemInfo {
      return MaaResultMaaSystemInfoToJSONTyped(json, false);
  }

  export function MaaResultMaaSystemInfoToJSONTyped(value?: MaaResultMaaSystemInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'message': value['message'],
        'data': MaaSystemInfoToJSON(value['data']),
    };
}

