/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CopilotSetPageRes } from './CopilotSetPageRes';
import {
    CopilotSetPageResFromJSON,
    CopilotSetPageResFromJSONTyped,
    CopilotSetPageResToJSON,
} from './CopilotSetPageRes';

/**
 * 
 * @export
 * @interface MaaResultCopilotSetPageRes
 */
export interface MaaResultCopilotSetPageRes {
    /**
     * 
     * @type {number}
     * @memberof MaaResultCopilotSetPageRes
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof MaaResultCopilotSetPageRes
     */
    message?: string;
    /**
     * 
     * @type {CopilotSetPageRes}
     * @memberof MaaResultCopilotSetPageRes
     */
    data?: CopilotSetPageRes;
}

/**
 * Check if a given object implements the MaaResultCopilotSetPageRes interface.
 */
export function instanceOfMaaResultCopilotSetPageRes(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "statusCode" in value;

    return isInstance;
}

export function MaaResultCopilotSetPageResFromJSON(json: any): MaaResultCopilotSetPageRes {
    return MaaResultCopilotSetPageResFromJSONTyped(json, false);
}

export function MaaResultCopilotSetPageResFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaaResultCopilotSetPageRes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : CopilotSetPageResFromJSON(json['data']),
    };
}

export function MaaResultCopilotSetPageResToJSON(value?: MaaResultCopilotSetPageRes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status_code': value.statusCode,
        'message': value.message,
        'data': CopilotSetPageResToJSON(value.data),
    };
}

