/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ArkLevelInfo } from './ArkLevelInfo';
import {
    ArkLevelInfoFromJSON,
    ArkLevelInfoFromJSONTyped,
    ArkLevelInfoToJSON,
} from './ArkLevelInfo';

/**
 * 
 * @export
 * @interface MaaResultListArkLevelInfo
 */
export interface MaaResultListArkLevelInfo {
    /**
     * 
     * @type {number}
     * @memberof MaaResultListArkLevelInfo
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof MaaResultListArkLevelInfo
     */
    message?: string;
    /**
     * 
     * @type {Array<ArkLevelInfo>}
     * @memberof MaaResultListArkLevelInfo
     */
    data?: Array<ArkLevelInfo>;
}

/**
 * Check if a given object implements the MaaResultListArkLevelInfo interface.
 */
export function instanceOfMaaResultListArkLevelInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "statusCode" in value;

    return isInstance;
}

export function MaaResultListArkLevelInfoFromJSON(json: any): MaaResultListArkLevelInfo {
    return MaaResultListArkLevelInfoFromJSONTyped(json, false);
}

export function MaaResultListArkLevelInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaaResultListArkLevelInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(ArkLevelInfoFromJSON)),
    };
}

export function MaaResultListArkLevelInfoToJSON(value?: MaaResultListArkLevelInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status_code': value.statusCode,
        'message': value.message,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(ArkLevelInfoToJSON)),
    };
}

