/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MaaResultString
 */
export interface MaaResultString {
    /**
     * 
     * @type {number}
     * @memberof MaaResultString
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof MaaResultString
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof MaaResultString
     */
    data?: string;
}

/**
 * Check if a given object implements the MaaResultString interface.
 */
export function instanceOfMaaResultString(value: object): value is MaaResultString {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function MaaResultStringFromJSON(json: any): MaaResultString {
    return MaaResultStringFromJSONTyped(json, false);
}

export function MaaResultStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaaResultString {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function MaaResultStringToJSON(json: any): MaaResultString {
    return MaaResultStringToJSONTyped(json, false);
}

export function MaaResultStringToJSONTyped(value?: MaaResultString | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'message': value['message'],
        'data': value['data'],
    };
}

