/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MaaLoginRsp } from './MaaLoginRsp';
import {
    MaaLoginRspFromJSON,
    MaaLoginRspFromJSONTyped,
    MaaLoginRspToJSON,
} from './MaaLoginRsp';

/**
 * 
 * @export
 * @interface MaaResultMaaLoginRsp
 */
export interface MaaResultMaaLoginRsp {
    /**
     * 
     * @type {number}
     * @memberof MaaResultMaaLoginRsp
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof MaaResultMaaLoginRsp
     */
    message?: string;
    /**
     * 
     * @type {MaaLoginRsp}
     * @memberof MaaResultMaaLoginRsp
     */
    data?: MaaLoginRsp;
}

/**
 * Check if a given object implements the MaaResultMaaLoginRsp interface.
 */
export function instanceOfMaaResultMaaLoginRsp(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "statusCode" in value;

    return isInstance;
}

export function MaaResultMaaLoginRspFromJSON(json: any): MaaResultMaaLoginRsp {
    return MaaResultMaaLoginRspFromJSONTyped(json, false);
}

export function MaaResultMaaLoginRspFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaaResultMaaLoginRsp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : MaaLoginRspFromJSON(json['data']),
    };
}

export function MaaResultMaaLoginRspToJSON(value?: MaaResultMaaLoginRsp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status_code': value.statusCode,
        'message': value.message,
        'data': MaaLoginRspToJSON(value.data),
    };
}

