/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CopilotSetPageRes } from './CopilotSetPageRes';
import {
    CopilotSetPageResFromJSON,
    CopilotSetPageResFromJSONTyped,
    CopilotSetPageResToJSON,
    CopilotSetPageResToJSONTyped,
} from './CopilotSetPageRes';

/**
 * 
 * @export
 * @interface MaaResultCopilotSetPageRes
 */
export interface MaaResultCopilotSetPageRes {
    /**
     * 
     * @type {number}
     * @memberof MaaResultCopilotSetPageRes
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof MaaResultCopilotSetPageRes
     */
    message?: string;
    /**
     * 
     * @type {CopilotSetPageRes}
     * @memberof MaaResultCopilotSetPageRes
     */
    data?: CopilotSetPageRes;
}

/**
 * Check if a given object implements the MaaResultCopilotSetPageRes interface.
 */
export function instanceOfMaaResultCopilotSetPageRes(value: object): value is MaaResultCopilotSetPageRes {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function MaaResultCopilotSetPageResFromJSON(json: any): MaaResultCopilotSetPageRes {
    return MaaResultCopilotSetPageResFromJSONTyped(json, false);
}

export function MaaResultCopilotSetPageResFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaaResultCopilotSetPageRes {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : CopilotSetPageResFromJSON(json['data']),
    };
}

export function MaaResultCopilotSetPageResToJSON(json: any): MaaResultCopilotSetPageRes {
    return MaaResultCopilotSetPageResToJSONTyped(json, false);
}

export function MaaResultCopilotSetPageResToJSONTyped(value?: MaaResultCopilotSetPageRes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'message': value['message'],
        'data': CopilotSetPageResToJSON(value['data']),
    };
}

