/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MaaUserInfo } from './MaaUserInfo';
import {
    MaaUserInfoFromJSON,
    MaaUserInfoFromJSONTyped,
    MaaUserInfoToJSON,
    MaaUserInfoToJSONTyped,
} from './MaaUserInfo';

/**
 * 
 * @export
 * @interface MaaResultMaaUserInfo
 */
export interface MaaResultMaaUserInfo {
    /**
     * 
     * @type {number}
     * @memberof MaaResultMaaUserInfo
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof MaaResultMaaUserInfo
     */
    message?: string;
    /**
     * 
     * @type {MaaUserInfo}
     * @memberof MaaResultMaaUserInfo
     */
    data?: MaaUserInfo;
}

/**
 * Check if a given object implements the MaaResultMaaUserInfo interface.
 */
export function instanceOfMaaResultMaaUserInfo(value: object): value is MaaResultMaaUserInfo {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function MaaResultMaaUserInfoFromJSON(json: any): MaaResultMaaUserInfo {
    return MaaResultMaaUserInfoFromJSONTyped(json, false);
}

export function MaaResultMaaUserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaaResultMaaUserInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : MaaUserInfoFromJSON(json['data']),
    };
}

export function MaaResultMaaUserInfoToJSON(json: any): MaaResultMaaUserInfo {
    return MaaResultMaaUserInfoToJSONTyped(json, false);
}

export function MaaResultMaaUserInfoToJSONTyped(value?: MaaResultMaaUserInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'message': value['message'],
        'data': MaaUserInfoToJSON(value['data']),
    };
}

