/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MaaUserInfo } from './MaaUserInfo';
import {
    MaaUserInfoFromJSON,
    MaaUserInfoFromJSONTyped,
    MaaUserInfoToJSON,
    MaaUserInfoToJSONTyped,
} from './MaaUserInfo';

/**
 * 
 * @export
 * @interface MaaResultListMaaUserInfo
 */
export interface MaaResultListMaaUserInfo {
    /**
     * 
     * @type {number}
     * @memberof MaaResultListMaaUserInfo
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof MaaResultListMaaUserInfo
     */
    message?: string;
    /**
     * 
     * @type {Array<MaaUserInfo>}
     * @memberof MaaResultListMaaUserInfo
     */
    data?: Array<MaaUserInfo>;
}

/**
 * Check if a given object implements the MaaResultListMaaUserInfo interface.
 */
export function instanceOfMaaResultListMaaUserInfo(value: object): value is MaaResultListMaaUserInfo {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function MaaResultListMaaUserInfoFromJSON(json: any): MaaResultListMaaUserInfo {
    return MaaResultListMaaUserInfoFromJSONTyped(json, false);
}

export function MaaResultListMaaUserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaaResultListMaaUserInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(MaaUserInfoFromJSON)),
    };
}

export function MaaResultListMaaUserInfoToJSON(json: any): MaaResultListMaaUserInfo {
    return MaaResultListMaaUserInfoToJSONTyped(json, false);
}

export function MaaResultListMaaUserInfoToJSONTyped(value?: MaaResultListMaaUserInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(MaaUserInfoToJSON)),
    };
}

