/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UnreadMessageCountInfo } from './UnreadMessageCountInfo';
import {
    UnreadMessageCountInfoFromJSON,
    UnreadMessageCountInfoFromJSONTyped,
    UnreadMessageCountInfoToJSON,
    UnreadMessageCountInfoToJSONTyped,
} from './UnreadMessageCountInfo';

/**
 * 
 * @export
 * @interface MaaResultUnreadMessageCountInfo
 */
export interface MaaResultUnreadMessageCountInfo {
    /**
     * 
     * @type {number}
     * @memberof MaaResultUnreadMessageCountInfo
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof MaaResultUnreadMessageCountInfo
     */
    message?: string | null;
    /**
     * 
     * @type {UnreadMessageCountInfo}
     * @memberof MaaResultUnreadMessageCountInfo
     */
    data?: UnreadMessageCountInfo | null;
}

/**
 * Check if a given object implements the MaaResultUnreadMessageCountInfo interface.
 */
export function instanceOfMaaResultUnreadMessageCountInfo(value: object): value is MaaResultUnreadMessageCountInfo {
    if ((!('statusCode' in value) && !('status_code' in value)) || (value['statusCode'] === undefined && value['status_code'] === undefined)) return false;
    return true;
}

export function MaaResultUnreadMessageCountInfoFromJSON(json: any): MaaResultUnreadMessageCountInfo {
    return MaaResultUnreadMessageCountInfoFromJSONTyped(json, false);
}

export function MaaResultUnreadMessageCountInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaaResultUnreadMessageCountInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : UnreadMessageCountInfoFromJSON(json['data']),
    };
}

export function MaaResultUnreadMessageCountInfoToJSON(json: any): MaaResultUnreadMessageCountInfo {
    return MaaResultUnreadMessageCountInfoToJSONTyped(json, false);
}

export function MaaResultUnreadMessageCountInfoToJSONTyped(value?: MaaResultUnreadMessageCountInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'message': value['message'],
        'data': UnreadMessageCountInfoToJSON(value['data']),
    };
}

