/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MaaResultBoolean
 */
export interface MaaResultBoolean {
    /**
     * 
     * @type {number}
     * @memberof MaaResultBoolean
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof MaaResultBoolean
     */
    message?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof MaaResultBoolean
     */
    data?: boolean | null;
}

/**
 * Check if a given object implements the MaaResultBoolean interface.
 */
export function instanceOfMaaResultBoolean(value: object): value is MaaResultBoolean {
    if ((!('statusCode' in value) && !('status_code' in value)) || (value['statusCode'] === undefined && value['status_code'] === undefined)) return false;
    return true;
}

export function MaaResultBooleanFromJSON(json: any): MaaResultBoolean {
    return MaaResultBooleanFromJSONTyped(json, false);
}

export function MaaResultBooleanFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaaResultBoolean {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function MaaResultBooleanToJSON(json: any): MaaResultBoolean {
    return MaaResultBooleanToJSONTyped(json, false);
}

export function MaaResultBooleanToJSONTyped(value?: MaaResultBoolean | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'message': value['message'],
        'data': value['data'],
    };
}

