/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UploadAbility } from './UploadAbility';
import {
    UploadAbilityFromJSON,
    UploadAbilityFromJSONTyped,
    UploadAbilityToJSON,
} from './UploadAbility';

/**
 * 
 * @export
 * @interface MaaResultUploadAbility
 */
export interface MaaResultUploadAbility {
    /**
     * 
     * @type {number}
     * @memberof MaaResultUploadAbility
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof MaaResultUploadAbility
     */
    message?: string;
    /**
     * 
     * @type {UploadAbility}
     * @memberof MaaResultUploadAbility
     */
    data?: UploadAbility;
}

/**
 * Check if a given object implements the MaaResultUploadAbility interface.
 */
export function instanceOfMaaResultUploadAbility(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "statusCode" in value;

    return isInstance;
}

export function MaaResultUploadAbilityFromJSON(json: any): MaaResultUploadAbility {
    return MaaResultUploadAbilityFromJSONTyped(json, false);
}

export function MaaResultUploadAbilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaaResultUploadAbility {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : UploadAbilityFromJSON(json['data']),
    };
}

export function MaaResultUploadAbilityToJSON(value?: MaaResultUploadAbility | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status_code': value.statusCode,
        'message': value.message,
        'data': UploadAbilityToJSON(value.data),
    };
}

