/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GitProperties } from './GitProperties';
import {
    GitPropertiesFromJSON,
    GitPropertiesFromJSONTyped,
    GitPropertiesToJSON,
    GitPropertiesToJSONTyped,
} from './GitProperties';

/**
 * 
 * @export
 * @interface MaaSystemInfo
 */
export interface MaaSystemInfo {
    /**
     * 
     * @type {string}
     * @memberof MaaSystemInfo
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof MaaSystemInfo
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof MaaSystemInfo
     */
    version: string;
    /**
     * 
     * @type {GitProperties}
     * @memberof MaaSystemInfo
     */
    git: GitProperties;
}

/**
 * Check if a given object implements the MaaSystemInfo interface.
 */
export function instanceOfMaaSystemInfo(value: object): value is MaaSystemInfo {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('git' in value) || value['git'] === undefined) return false;
    return true;
}

export function MaaSystemInfoFromJSON(json: any): MaaSystemInfo {
    return MaaSystemInfoFromJSONTyped(json, false);
}

export function MaaSystemInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaaSystemInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'version': json['version'],
        'git': GitPropertiesFromJSON(json['git']),
    };
}

export function MaaSystemInfoToJSON(json: any): MaaSystemInfo {
    return MaaSystemInfoToJSONTyped(json, false);
}

export function MaaSystemInfoToJSONTyped(value?: MaaSystemInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'version': value['version'],
        'git': GitPropertiesToJSON(value['git']),
    };
}

