/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GitProperties } from './GitProperties';
import {
    GitPropertiesFromJSON,
    GitPropertiesFromJSONTyped,
    GitPropertiesToJSON,
} from './GitProperties';

/**
 * 
 * @export
 * @interface MaaSystemInfo
 */
export interface MaaSystemInfo {
    /**
     * 
     * @type {string}
     * @memberof MaaSystemInfo
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof MaaSystemInfo
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof MaaSystemInfo
     */
    version: string;
    /**
     * 
     * @type {GitProperties}
     * @memberof MaaSystemInfo
     */
    git: GitProperties;
}

/**
 * Check if a given object implements the MaaSystemInfo interface.
 */
export function instanceOfMaaSystemInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "version" in value;
    isInstance = isInstance && "git" in value;

    return isInstance;
}

export function MaaSystemInfoFromJSON(json: any): MaaSystemInfo {
    return MaaSystemInfoFromJSONTyped(json, false);
}

export function MaaSystemInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaaSystemInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'version': json['version'],
        'git': GitPropertiesFromJSON(json['git']),
    };
}

export function MaaSystemInfoToJSON(value?: MaaSystemInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'version': value.version,
        'git': GitPropertiesToJSON(value.git),
    };
}

