/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GitInfo } from './GitInfo';
import {
    GitInfoFromJSON,
    GitInfoFromJSONTyped,
    GitInfoToJSON,
    GitInfoToJSONTyped,
} from './GitInfo';

/**
 * 
 * @export
 * @interface MaaSystemInfo
 */
export interface MaaSystemInfo {
    /**
     * 
     * @type {string}
     * @memberof MaaSystemInfo
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof MaaSystemInfo
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof MaaSystemInfo
     */
    version?: string;
    /**
     * 
     * @type {GitInfo}
     * @memberof MaaSystemInfo
     */
    git?: GitInfo;
}

/**
 * Check if a given object implements the MaaSystemInfo interface.
 */
export function instanceOfMaaSystemInfo(value: object): value is MaaSystemInfo {
    return true;
}

export function MaaSystemInfoFromJSON(json: any): MaaSystemInfo {
    return MaaSystemInfoFromJSONTyped(json, false);
}

export function MaaSystemInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaaSystemInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'version': json['version'] == null ? undefined : json['version'],
        'git': json['git'] == null ? undefined : GitInfoFromJSON(json['git']),
    };
}

export function MaaSystemInfoToJSON(json: any): MaaSystemInfo {
    return MaaSystemInfoToJSONTyped(json, false);
}

export function MaaSystemInfoToJSONTyped(value?: MaaSystemInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'version': value['version'],
        'git': GitInfoToJSON(value['git']),
    };
}

