/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 用户可对外公开的信息
 * @export
 * @interface MaaUserInfo
 */
export interface MaaUserInfo {
    /**
     * 
     * @type {string}
     * @memberof MaaUserInfo
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof MaaUserInfo
     */
    userName: string;
    /**
     * 
     * @type {boolean}
     * @memberof MaaUserInfo
     */
    activated: boolean;
}

/**
 * Check if a given object implements the MaaUserInfo interface.
 */
export function instanceOfMaaUserInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "userName" in value;
    isInstance = isInstance && "activated" in value;

    return isInstance;
}

export function MaaUserInfoFromJSON(json: any): MaaUserInfo {
    return MaaUserInfoFromJSONTyped(json, false);
}

export function MaaUserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaaUserInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userName': json['user_name'],
        'activated': json['activated'],
    };
}

export function MaaUserInfoToJSON(value?: MaaUserInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'user_name': value.userName,
        'activated': value.activated,
    };
}

