/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MaaUserInfo
 */
export interface MaaUserInfo {
    /**
     * 
     * @type {string}
     * @memberof MaaUserInfo
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof MaaUserInfo
     */
    userName: string;
    /**
     * 
     * @type {boolean}
     * @memberof MaaUserInfo
     */
    activated: boolean;
    /**
     * 
     * @type {number}
     * @memberof MaaUserInfo
     */
    followingCount: number;
    /**
     * 
     * @type {number}
     * @memberof MaaUserInfo
     */
    fansCount: number;
}

/**
 * Check if a given object implements the MaaUserInfo interface.
 */
export function instanceOfMaaUserInfo(value: object): value is MaaUserInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userName' in value) || value['userName'] === undefined) return false;
    if (!('activated' in value) || value['activated'] === undefined) return false;
    if (!('followingCount' in value) || value['followingCount'] === undefined) return false;
    if (!('fansCount' in value) || value['fansCount'] === undefined) return false;
    return true;
}

export function MaaUserInfoFromJSON(json: any): MaaUserInfo {
    return MaaUserInfoFromJSONTyped(json, false);
}

export function MaaUserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaaUserInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userName': json['user_name'],
        'activated': json['activated'],
        'followingCount': json['following_count'],
        'fansCount': json['fans_count'],
    };
}

export function MaaUserInfoToJSON(json: any): MaaUserInfo {
    return MaaUserInfoToJSONTyped(json, false);
}

export function MaaUserInfoToJSONTyped(value?: MaaUserInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_name': value['userName'],
        'activated': value['activated'],
        'following_count': value['followingCount'],
        'fans_count': value['fansCount'],
    };
}

