/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CopilotSetListRes } from './CopilotSetListRes';
import {
    CopilotSetListResFromJSON,
    CopilotSetListResFromJSONTyped,
    CopilotSetListResToJSON,
    CopilotSetListResToJSONTyped,
} from './CopilotSetListRes';

/**
 * 
 * @export
 * @interface PagedDTOCopilotSetListRes
 */
export interface PagedDTOCopilotSetListRes {
    /**
     * 
     * @type {boolean}
     * @memberof PagedDTOCopilotSetListRes
     */
    hasNext?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PagedDTOCopilotSetListRes
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedDTOCopilotSetListRes
     */
    total?: number;
    /**
     * 
     * @type {Array<CopilotSetListRes>}
     * @memberof PagedDTOCopilotSetListRes
     */
    data?: Array<CopilotSetListRes>;
}

/**
 * Check if a given object implements the PagedDTOCopilotSetListRes interface.
 */
export function instanceOfPagedDTOCopilotSetListRes(value: object): value is PagedDTOCopilotSetListRes {
    return true;
}

export function PagedDTOCopilotSetListResFromJSON(json: any): PagedDTOCopilotSetListRes {
    return PagedDTOCopilotSetListResFromJSONTyped(json, false);
}

export function PagedDTOCopilotSetListResFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedDTOCopilotSetListRes {
    if (json == null) {
        return json;
    }
    return {
        
        'hasNext': json['has_next'] == null ? undefined : json['has_next'],
        'page': json['page'] == null ? undefined : json['page'],
        'total': json['total'] == null ? undefined : json['total'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(CopilotSetListResFromJSON)),
    };
}

export function PagedDTOCopilotSetListResToJSON(json: any): PagedDTOCopilotSetListRes {
    return PagedDTOCopilotSetListResToJSONTyped(json, false);
}

export function PagedDTOCopilotSetListResToJSONTyped(value?: PagedDTOCopilotSetListRes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'has_next': value['hasNext'],
        'page': value['page'],
        'total': value['total'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(CopilotSetListResToJSON)),
    };
}

