/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SiteMessageInfo } from './SiteMessageInfo';
import {
    SiteMessageInfoFromJSON,
    SiteMessageInfoFromJSONTyped,
    SiteMessageInfoToJSON,
    SiteMessageInfoToJSONTyped,
} from './SiteMessageInfo';

/**
 * 
 * @export
 * @interface PagedDTOSiteMessageInfo
 */
export interface PagedDTOSiteMessageInfo {
    /**
     * 
     * @type {boolean}
     * @memberof PagedDTOSiteMessageInfo
     */
    hasNext: boolean;
    /**
     * 
     * @type {number}
     * @memberof PagedDTOSiteMessageInfo
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PagedDTOSiteMessageInfo
     */
    total: number;
    /**
     * 
     * @type {Array<SiteMessageInfo>}
     * @memberof PagedDTOSiteMessageInfo
     */
    data: Array<SiteMessageInfo>;
}

/**
 * Check if a given object implements the PagedDTOSiteMessageInfo interface.
 */
export function instanceOfPagedDTOSiteMessageInfo(value: object): value is PagedDTOSiteMessageInfo {
    if ((!('hasNext' in value) && !('has_next' in value)) || (value['hasNext'] === undefined && value['has_next'] === undefined)) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PagedDTOSiteMessageInfoFromJSON(json: any): PagedDTOSiteMessageInfo {
    return PagedDTOSiteMessageInfoFromJSONTyped(json, false);
}

export function PagedDTOSiteMessageInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedDTOSiteMessageInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'hasNext': json['has_next'],
        'page': json['page'],
        'total': json['total'],
        'data': ((json['data'] as Array<any>).map(SiteMessageInfoFromJSON)),
    };
}

export function PagedDTOSiteMessageInfoToJSON(json: any): PagedDTOSiteMessageInfo {
    return PagedDTOSiteMessageInfoToJSONTyped(json, false);
}

export function PagedDTOSiteMessageInfoToJSONTyped(value?: PagedDTOSiteMessageInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'has_next': value['hasNext'],
        'page': value['page'],
        'total': value['total'],
        'data': ((value['data'] as Array<any>).map(SiteMessageInfoToJSON)),
    };
}

