/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MaaUserInfo } from './MaaUserInfo';
import {
    MaaUserInfoFromJSON,
    MaaUserInfoFromJSONTyped,
    MaaUserInfoToJSON,
    MaaUserInfoToJSONTyped,
} from './MaaUserInfo';

/**
 * 
 * @export
 * @interface PagedDTOMaaUserInfo
 */
export interface PagedDTOMaaUserInfo {
    /**
     * 
     * @type {boolean}
     * @memberof PagedDTOMaaUserInfo
     */
    hasNext: boolean;
    /**
     * 
     * @type {number}
     * @memberof PagedDTOMaaUserInfo
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PagedDTOMaaUserInfo
     */
    total: number;
    /**
     * 
     * @type {Array<MaaUserInfo>}
     * @memberof PagedDTOMaaUserInfo
     */
    data: Array<MaaUserInfo>;
}

/**
 * Check if a given object implements the PagedDTOMaaUserInfo interface.
 */
export function instanceOfPagedDTOMaaUserInfo(value: object): value is PagedDTOMaaUserInfo {
    if (!('hasNext' in value) || value['hasNext'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PagedDTOMaaUserInfoFromJSON(json: any): PagedDTOMaaUserInfo {
    return PagedDTOMaaUserInfoFromJSONTyped(json, false);
}

export function PagedDTOMaaUserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedDTOMaaUserInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'hasNext': json['has_next'],
        'page': json['page'],
        'total': json['total'],
        'data': ((json['data'] as Array<any>).map(MaaUserInfoFromJSON)),
    };
}

export function PagedDTOMaaUserInfoToJSON(json: any): PagedDTOMaaUserInfo {
    return PagedDTOMaaUserInfoToJSONTyped(json, false);
}

export function PagedDTOMaaUserInfoToJSONTyped(value?: PagedDTOMaaUserInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'has_next': value['hasNext'],
        'page': value['page'],
        'total': value['total'],
        'data': ((value['data'] as Array<any>).map(MaaUserInfoToJSON)),
    };
}

