/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasswordUpdateDTO
 */
export interface PasswordUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof PasswordUpdateDTO
     */
    originalPassword: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordUpdateDTO
     */
    newPassword: string;
}

/**
 * Check if a given object implements the PasswordUpdateDTO interface.
 */
export function instanceOfPasswordUpdateDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "originalPassword" in value;
    isInstance = isInstance && "newPassword" in value;

    return isInstance;
}

export function PasswordUpdateDTOFromJSON(json: any): PasswordUpdateDTO {
    return PasswordUpdateDTOFromJSONTyped(json, false);
}

export function PasswordUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'originalPassword': json['original_password'],
        'newPassword': json['new_password'],
    };
}

export function PasswordUpdateDTOToJSON(value?: PasswordUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'original_password': value.originalPassword,
        'new_password': value.newPassword,
    };
}

