/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 通过邮件修改密码请求
 * @export
 * @interface PasswordResetDTO
 */
export interface PasswordResetDTO {
    /**
     * 邮箱
     * @type {string}
     * @memberof PasswordResetDTO
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordResetDTO
     */
    activeCode: string;
    /**
     * 修改后的密码
     * @type {string}
     * @memberof PasswordResetDTO
     */
    password: string;
}

/**
 * Check if a given object implements the PasswordResetDTO interface.
 */
export function instanceOfPasswordResetDTO(value: object): value is PasswordResetDTO {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('activeCode' in value) || value['activeCode'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function PasswordResetDTOFromJSON(json: any): PasswordResetDTO {
    return PasswordResetDTOFromJSONTyped(json, false);
}

export function PasswordResetDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordResetDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'activeCode': json['active_code'],
        'password': json['password'],
    };
}

  export function PasswordResetDTOToJSON(json: any): PasswordResetDTO {
      return PasswordResetDTOToJSONTyped(json, false);
  }

  export function PasswordResetDTOToJSONTyped(value?: PasswordResetDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'active_code': value['activeCode'],
        'password': value['password'],
    };
}

