/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasswordResetVCodeDTO
 */
export interface PasswordResetVCodeDTO {
    /**
     * 
     * @type {string}
     * @memberof PasswordResetVCodeDTO
     */
    email: string;
}

/**
 * Check if a given object implements the PasswordResetVCodeDTO interface.
 */
export function instanceOfPasswordResetVCodeDTO(value: object): value is PasswordResetVCodeDTO {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function PasswordResetVCodeDTOFromJSON(json: any): PasswordResetVCodeDTO {
    return PasswordResetVCodeDTOFromJSONTyped(json, false);
}

export function PasswordResetVCodeDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordResetVCodeDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function PasswordResetVCodeDTOToJSON(json: any): PasswordResetVCodeDTO {
    return PasswordResetVCodeDTOToJSONTyped(json, false);
}

export function PasswordResetVCodeDTOToJSONTyped(value?: PasswordResetVCodeDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

