/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 通过邮件修改密码请求
 * @export
 * @interface PasswordResetDTO
 */
export interface PasswordResetDTO {
    /**
     * 邮箱
     * @type {string}
     * @memberof PasswordResetDTO
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordResetDTO
     */
    activeCode: string;
    /**
     * 修改后的密码
     * @type {string}
     * @memberof PasswordResetDTO
     */
    password: string;
}

/**
 * Check if a given object implements the PasswordResetDTO interface.
 */
export function instanceOfPasswordResetDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "activeCode" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function PasswordResetDTOFromJSON(json: any): PasswordResetDTO {
    return PasswordResetDTOFromJSONTyped(json, false);
}

export function PasswordResetDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordResetDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'activeCode': json['active_code'],
        'password': json['password'],
    };
}

export function PasswordResetDTOToJSON(value?: PasswordResetDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'active_code': value.activeCode,
        'password': value.password,
    };
}

