/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 通过邮件修改密码发送验证码请求
 * @export
 * @interface PasswordResetVCodeDTO
 */
export interface PasswordResetVCodeDTO {
    /**
     * 邮箱
     * @type {string}
     * @memberof PasswordResetVCodeDTO
     */
    email: string;
}

/**
 * Check if a given object implements the PasswordResetVCodeDTO interface.
 */
export function instanceOfPasswordResetVCodeDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function PasswordResetVCodeDTOFromJSON(json: any): PasswordResetVCodeDTO {
    return PasswordResetVCodeDTOFromJSONTyped(json, false);
}

export function PasswordResetVCodeDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordResetVCodeDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function PasswordResetVCodeDTOToJSON(value?: PasswordResetVCodeDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

