/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasswordUpdateDTO
 */
export interface PasswordUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof PasswordUpdateDTO
     */
    originalPassword: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordUpdateDTO
     */
    newPassword: string;
}

/**
 * Check if a given object implements the PasswordUpdateDTO interface.
 */
export function instanceOfPasswordUpdateDTO(value: object): value is PasswordUpdateDTO {
    if (!('originalPassword' in value) || value['originalPassword'] === undefined) return false;
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    return true;
}

export function PasswordUpdateDTOFromJSON(json: any): PasswordUpdateDTO {
    return PasswordUpdateDTOFromJSONTyped(json, false);
}

export function PasswordUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordUpdateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'originalPassword': json['original_password'],
        'newPassword': json['new_password'],
    };
}

  export function PasswordUpdateDTOToJSON(json: any): PasswordUpdateDTO {
      return PasswordUpdateDTOToJSONTyped(json, false);
  }

  export function PasswordUpdateDTOToJSONTyped(value?: PasswordUpdateDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'original_password': value['originalPassword'],
        'new_password': value['newPassword'],
    };
}

