/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CopilotCUDRequest } from './CopilotCUDRequest';
import {
    CopilotCUDRequestFromJSON,
    CopilotCUDRequestFromJSONTyped,
    CopilotCUDRequestToJSON,
    CopilotCUDRequestToJSONTyped,
} from './CopilotCUDRequest';

/**
 * 
 * @export
 * @interface PrtsCUDRequest
 */
export interface PrtsCUDRequest extends CopilotCUDRequest {
    /**
     * 
     * @type {string}
     * @memberof PrtsCUDRequest
     */
    content: string;
    /**
     * 
     * @type {number}
     * @memberof PrtsCUDRequest
     */
    id?: number | null;
    /**
     * 
     * @type {PrtsCUDRequestStatusEnum}
     * @memberof PrtsCUDRequest
     */
    status: PrtsCUDRequestStatusEnum;
}


/**
 * @export
 */
export const PrtsCUDRequestStatusEnum = {
    Private: 'PRIVATE',
    Public: 'PUBLIC'
} as const;
export type PrtsCUDRequestStatusEnum = typeof PrtsCUDRequestStatusEnum[keyof typeof PrtsCUDRequestStatusEnum];


/**
 * Check if a given object implements the PrtsCUDRequest interface.
 */
export function instanceOfPrtsCUDRequest(value: object): value is PrtsCUDRequest {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function PrtsCUDRequestFromJSON(json: any): PrtsCUDRequest {
    return PrtsCUDRequestFromJSONTyped(json, false);
}

export function PrtsCUDRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrtsCUDRequest {
    if (json == null) {
        return json;
    }
    return {
        ...CopilotCUDRequestFromJSONTyped(json, true),
        'content': json['content'],
        'id': json['id'] == null ? undefined : json['id'],
        'status': json['status'],
    };
}

export function PrtsCUDRequestToJSON(json: any): PrtsCUDRequest {
    return PrtsCUDRequestToJSONTyped(json, false);
}

export function PrtsCUDRequestToJSONTyped(value?: PrtsCUDRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...CopilotCUDRequestToJSONTyped(value, true),
        'content': value['content'],
        'id': value['id'],
        'status': value['status'],
    };
}

