/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterDTO
 */
export interface RegisterDTO {
    /**
     * 
     * @type {string}
     * @memberof RegisterDTO
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterDTO
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterDTO
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterDTO
     */
    registrationToken: string;
}

/**
 * Check if a given object implements the RegisterDTO interface.
 */
export function instanceOfRegisterDTO(value: object): value is RegisterDTO {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('userName' in value) || value['userName'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('registrationToken' in value) || value['registrationToken'] === undefined) return false;
    return true;
}

export function RegisterDTOFromJSON(json: any): RegisterDTO {
    return RegisterDTOFromJSONTyped(json, false);
}

export function RegisterDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'userName': json['user_name'],
        'password': json['password'],
        'registrationToken': json['registration_token'],
    };
}

  export function RegisterDTOToJSON(json: any): RegisterDTO {
      return RegisterDTOToJSONTyped(json, false);
  }

  export function RegisterDTOToJSONTyped(value?: RegisterDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'user_name': value['userName'],
        'password': value['password'],
        'registration_token': value['registrationToken'],
    };
}

