/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterDTO
 */
export interface RegisterDTO {
    /**
     * 
     * @type {string}
     * @memberof RegisterDTO
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterDTO
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterDTO
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterDTO
     */
    registrationToken: string;
}

/**
 * Check if a given object implements the RegisterDTO interface.
 */
export function instanceOfRegisterDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "userName" in value;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "registrationToken" in value;

    return isInstance;
}

export function RegisterDTOFromJSON(json: any): RegisterDTO {
    return RegisterDTOFromJSONTyped(json, false);
}

export function RegisterDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'userName': json['user_name'],
        'password': json['password'],
        'registrationToken': json['registration_token'],
    };
}

export function RegisterDTOToJSON(value?: RegisterDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'user_name': value.userName,
        'password': value.password,
        'registration_token': value.registrationToken,
    };
}

