/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendRegistrationTokenDTO
 */
export interface SendRegistrationTokenDTO {
    /**
     * 
     * @type {string}
     * @memberof SendRegistrationTokenDTO
     */
    email: string;
}

/**
 * Check if a given object implements the SendRegistrationTokenDTO interface.
 */
export function instanceOfSendRegistrationTokenDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function SendRegistrationTokenDTOFromJSON(json: any): SendRegistrationTokenDTO {
    return SendRegistrationTokenDTOFromJSONTyped(json, false);
}

export function SendRegistrationTokenDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendRegistrationTokenDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function SendRegistrationTokenDTOToJSON(value?: SendRegistrationTokenDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

