/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubCommentsInfo
 */
export interface SubCommentsInfo {
    /**
     * 
     * @type {number}
     * @memberof SubCommentsInfo
     */
    commentId?: number;
    /**
     * 
     * @type {string}
     * @memberof SubCommentsInfo
     */
    uploader?: string;
    /**
     * 
     * @type {string}
     * @memberof SubCommentsInfo
     */
    uploaderId?: string;
    /**
     * 
     * @type {string}
     * @memberof SubCommentsInfo
     */
    message?: string;
    /**
     * 
     * @type {Date}
     * @memberof SubCommentsInfo
     */
    uploadTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof SubCommentsInfo
     */
    like?: number;
    /**
     * 
     * @type {number}
     * @memberof SubCommentsInfo
     */
    dislike?: number;
    /**
     * 
     * @type {number}
     * @memberof SubCommentsInfo
     */
    fromCommentId?: number;
    /**
     * 
     * @type {number}
     * @memberof SubCommentsInfo
     */
    mainCommentId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SubCommentsInfo
     */
    deleted?: boolean;
}

/**
 * Check if a given object implements the SubCommentsInfo interface.
 */
export function instanceOfSubCommentsInfo(value: object): value is SubCommentsInfo {
    return true;
}

export function SubCommentsInfoFromJSON(json: any): SubCommentsInfo {
    return SubCommentsInfoFromJSONTyped(json, false);
}

export function SubCommentsInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubCommentsInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'commentId': json['comment_id'] == null ? undefined : json['comment_id'],
        'uploader': json['uploader'] == null ? undefined : json['uploader'],
        'uploaderId': json['uploader_id'] == null ? undefined : json['uploader_id'],
        'message': json['message'] == null ? undefined : json['message'],
        'uploadTime': json['upload_time'] == null ? undefined : (new Date(json['upload_time'])),
        'like': json['like'] == null ? undefined : json['like'],
        'dislike': json['dislike'] == null ? undefined : json['dislike'],
        'fromCommentId': json['from_comment_id'] == null ? undefined : json['from_comment_id'],
        'mainCommentId': json['main_comment_id'] == null ? undefined : json['main_comment_id'],
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
    };
}

export function SubCommentsInfoToJSON(json: any): SubCommentsInfo {
    return SubCommentsInfoToJSONTyped(json, false);
}

export function SubCommentsInfoToJSONTyped(value?: SubCommentsInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comment_id': value['commentId'],
        'uploader': value['uploader'],
        'uploader_id': value['uploaderId'],
        'message': value['message'],
        'upload_time': value['uploadTime'] == null ? value['uploadTime'] : value['uploadTime'].toISOString(),
        'like': value['like'],
        'dislike': value['dislike'],
        'from_comment_id': value['fromCommentId'],
        'main_comment_id': value['mainCommentId'],
        'deleted': value['deleted'],
    };
}

