/* tslint:disable */
/* eslint-disable */
/**
 * MAA Copilot Center API
 * MAA Copilot Backend Center
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadAbility
 */
export interface UploadAbility {
    /**
     * 
     * @type {boolean}
     * @memberof UploadAbility
     */
    enabled: boolean;
}

/**
 * Check if a given object implements the UploadAbility interface.
 */
export function instanceOfUploadAbility(value: object): value is UploadAbility {
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    return true;
}

export function UploadAbilityFromJSON(json: any): UploadAbility {
    return UploadAbilityFromJSONTyped(json, false);
}

export function UploadAbilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadAbility {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
    };
}

export function UploadAbilityToJSON(json: any): UploadAbility {
    return UploadAbilityToJSONTyped(json, false);
}

export function UploadAbilityToJSONTyped(value?: UploadAbility | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
    };
}

