/* tslint:disable */
/* eslint-disable */
/**
 * ZOOT Plus Backend API
 * ZOOT Plus Backend API
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PrtsCUDRequest } from './PrtsCUDRequest';
import {
    instanceOfPrtsCUDRequest,
    PrtsCUDRequestFromJSON,
    PrtsCUDRequestFromJSONTyped,
    PrtsCUDRequestToJSON,
} from './PrtsCUDRequest';
import type { VideoCUDRequest } from './VideoCUDRequest';
import {
    instanceOfVideoCUDRequest,
    VideoCUDRequestFromJSON,
    VideoCUDRequestFromJSONTyped,
    VideoCUDRequestToJSON,
} from './VideoCUDRequest';

/**
 * @type UploadCopilotRequest
 * 
 * @export
 */
export type UploadCopilotRequest = PrtsCUDRequest | VideoCUDRequest;

export function UploadCopilotRequestFromJSON(json: any): UploadCopilotRequest {
    return UploadCopilotRequestFromJSONTyped(json, false);
}

export function UploadCopilotRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadCopilotRequest {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfPrtsCUDRequest(json)) {
        return PrtsCUDRequestFromJSONTyped(json, true);
    }
    if (instanceOfVideoCUDRequest(json)) {
        return VideoCUDRequestFromJSONTyped(json, true);
    }
    return {} as any;
}

export function UploadCopilotRequestToJSON(json: any): any {
    return UploadCopilotRequestToJSONTyped(json, false);
}

export function UploadCopilotRequestToJSONTyped(value?: UploadCopilotRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfPrtsCUDRequest(value)) {
        return PrtsCUDRequestToJSON(value as PrtsCUDRequest);
    }
    if (instanceOfVideoCUDRequest(value)) {
        return VideoCUDRequestToJSON(value as VideoCUDRequest);
    }
    return {};
}

